### ISSUE TITLE
 请求适配无障碍语音控制

### ISSUE THREAD

**Issue by xiaowine** [BetterAndroid/android-notification-icon-project#124]
![Screenshot_2022-07-11-23-40-14-748_com miui home](https://user-images.githubusercontent.com/68009112/178303444-07022bc1-514a-4b93-8249-d101c86d5c8c.jpg)
![Screenshot_2022-07-11-23-44-41-298_com miui home](https://user-images.githubusercontent.com/68009112/178303657-fd6b0727-235f-44b3-9bbf-aa8e3b89e538.jpg)

请求适配小米无障碍 
包名com.miui.accessibility

**Comment by fankes** [comment]
issues 格式无效，此 repo 不接受适配反馈，请提交到正确位置或 PR
