### ISSUE TITLE
中国移动云盘APP

### ISSUE THREAD

**Issue by wuyulunbiJay** [BetterAndroid/android-notification-icon-project#191]
请求适配中国移动云盘APP.
![1](https://user-images.githubusercontent.com/115518225/194994509-4a7bf146-6f73-4ac2-9711-11afbc156f1f.jpg)
Thanks

**Comment by fankes** [comment]
@NekoMua 

com.chinamobile.mcloud

**Comment by wuyulunbiJay** [comment]
反馈一下哈，中午这是显示已经适配了的，我看了下哈，包名填错啦，填到微店去了
![2](https://user-images.githubusercontent.com/115518225/195047692-61a77923-fe66-4c3a-aa57-be9c9b7bcff3.jpg)

**Comment by fankes** [comment]
@NekoMua 我也没看，上面发你包名了，有空改一下233

**Comment by fankes** [comment]
已修复
