### ISSUE TITLE
[Request] 同花顺投资记账本

### ISSUE THREAD

**Issue by wuyulunbiJay** [BetterAndroid/android-notification-icon-project#198]
### APP 名称

同花顺投资记账本

### APP 包名

com.hexin.zhanghu

### 下载渠道、来源地址链接

酷安

### 简单描述适配的通知图标使用场景

小米推送的为彩色图标

### 通知单色图标适配素材 (大小 50x50~72x72)

完美图标，没有这个包名....所以没有图

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
