### ISSUE TITLE
关于图标大小的适配问题

### ISSUE THREAD

**Issue by piscesmk2013** [BetterAndroid/android-notification-icon-project#208]
我在A13类原生ROM使用noticefix导入图标库之后，发现有些图标在状态栏偏小，我将图标的base64转为图片后发现图标只有50x50，而正常大小的图标是72x72，我想问问，如果我将我遇上的偏小的图标重新制作为72x72，并转为base64 push上来后会对您的其他项目有影响吗？

**Comment by fankes** [comment]
不会，图标资源欢迎自由贡献

**Comment by fankes** [comment]
noticefix是什么
