### ISSUE TITLE
[Request] 请求适配蚂蚁财富

### ISSUE THREAD

**Issue by 849506054** [BetterAndroid/android-notification-icon-project#227]
### APP 名称

蚂蚁财富

### APP 包名

com.antfortune.wealth

### 下载渠道、来源地址链接

https://t.alipayobjects.com/L1/71/701/6068/AntFortune.apk

### 简单描述适配的通知图标使用场景

hms推送图标不规范
![Screenshot_20221115-141148__01](https://user-images.githubusercontent.com/25845909/201840269-f1975e43-b523-4064-af44-857c2494dec3.jpg)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
