### ISSUE TITLE
[Request] 奥比岛(小米服)

### ISSUE THREAD

**Issue by Mc-user1688** [BetterAndroid/android-notification-icon-project#229]
### APP 名称

奥比岛(小米服)

### APP 包名

com.baitian.aobi.czs.mi

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by DieMoon98** [comment]
APP 名称
中国移动河南

APP 包名
com.xinhang.mobileclient

通知图标颜色 (HEX)
No response

下载渠道、来源地址链接
华为应用商店

简单描述适配的通知图标使用场景
HMS推送

通知单色图标适配素材 (大小 50x50~72x72)
No response
