### ISSUE TITLE
[Request] 滴宠生活

### ISSUE THREAD

**Issue by xixiha5230** [BetterAndroid/android-notification-icon-project#231]
### APP 名称

滴宠生活

### APP 包名

com.mxchip.petmarvel

### 下载渠道、来源地址链接

https://sj.qq.com/appdetail/com.mxchip.petmarvel

### 简单描述适配的通知图标使用场景

在原生系统上，这个app的通知图标为白色方块

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
