### ISSUE TITLE
[Request] 武汉政务

### ISSUE THREAD

**Issue by mophisgy** [BetterAndroid/android-notification-icon-project#240]
### APP 名称

武汉政务

### APP 包名

com.tencent.weworklocal

### 下载渠道、来源地址链接

http://big.vshitech.com/filebig/100/com.tencent.weworklocal_v2.6.210000_itmop.com.apk

### 简单描述适配的通知图标使用场景

HMS推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by mophisgy** [comment]
您好，邮件已收到，谢谢。顺祝健康开心。
