### ISSUE TITLE
[Request] 脉脉

### ISSUE THREAD

**Issue by LamKwong-99** [BetterAndroid/android-notification-icon-project#241]
### APP 名称

脉脉

### APP 包名

com.taou.maimai

### 通知图标颜色 (HEX)

#ff0351fc

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

小米推送

### 通知单色图标适配素材 (大小 50x50~72x72)

iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAOCSURBVGhD7ZlBbtUwEIbfY4PEqmxZtSeg3bBASLQnoGzY0p6A9gSFExROQJHYF07wyglaTtAeAKnlBI//T8aRO892xonN6yKfNBr7JU4yHs94kjebmJhIMhfdsVwu30E9a3smrubz+YW0V8D1nkPttb0sznDdO2nngxufQ3LZl+Er4NhJe0o2t3IJE49Ej2VTdEk2YIz5uqUMWTv/w5Ch6zxrnMUQBvJTT7YgZhCwX6D88VbZwtgb6GFgXepgX8ihBvS5djVHcnhthNLvOZSfhS4wM136xPENKJ1RjnHOZ2m7c6KZTIOxZ9IsBw2B+GR7BP3N9mcz9+4xhIeStUan7weffuGtfci2dKPUMmR4aSHg4bmET9H8ClmgnfSaxZBmh3WCfu8yQPDSkCaFRiQZ3LgPkwWNYOyxTbmE2MFFhtRaWekX55+2wzqu5RCPccJiz3Aip61QdGnhRq8gXNMp4ewGwbFdKJ3+HUzv39qmAVxssEegLZXuNUR75BbCsdQhop5wrCNrhTzC3z6K9mGsHSLmPrXdOBZDriBvlYzBWj/RiD3rrm8x5A4X++EE/ejbIPgrOkVqvIPn0AhOoomiSws3ZkAy7e6IHEM0P0XH4GRxOZmNIMVjBA9AD/I9PvQgXC59D8jx2eV77WB/I9pBA/t2/QNkqezaq5oh8jD6gSzxQbiXZFHTIyFDfonuYxsTwc3RTE1DdMXKdR9b+1xuesmxWDRjMWQXs3PpBH3rS5COD75ppgzR+wVrLrNXrB7h7PqSBA/AHVovq75MxI8U2issZaK1mU+tpRWKj9+ig4i3uIf4cNJMXqllyHvRDj6kJWOFNlC+l/RiMYQb2KGSPvTyuzHsH+6FrPsaIzBWDqRtB4NGfUVBmzfW5fi9Mhz91IsVr89S36f3g3aNpcXY0AHaV191iFcY+D40LumVGoa8Fu1oai9pm8D5XF46yyUzWA1DdHxYyxKNfpmiER/a5ipFDZEZ0+/b1rJEw1SsE8RRzCulPRLK+YM8IrGiM2TUK6UN4f+FPky7WfGh4CTo8fSK3myre2SMEc4rplipbcjQ+OiAMf53AmYy7v4rX1VKG8L3dX5l4acda1ligQ/OlLzD1CyeSoP1N/r/kT5wfnRnH0roH6uXUC/aXsMfzMB3afP4EygWhY+bH1oWOCdZ3frgGrqq5aZZ/l+riYkJYTb7B3YtmU/MyrHiAAAAAElFTkSuQmCC

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NEKO

**Comment by fankes** [comment]
@NekoMua
