### ISSUE TITLE
[Request] 牛客

### ISSUE THREAD

**Issue by LamKwong-99** [BetterAndroid/android-notification-icon-project#242]
### APP 名称

牛客

### APP 包名

com.nowcoder.app.florida

### 通知图标颜色 (HEX)

#ff01dfa6

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

小米推送

### 通知单色图标适配素材 (大小 50x50~72x72)

iVBORw0KGgoAAAANSUhEUgAAADwAAAAyCAYAAAAA9rgCAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAS0SURBVGhD7ZpNiB41GMf3tRbptrJtqQVtrSKiiFYRWgTxo4i0elRQ6UERD+JVPPYueqjH9uahx156LvRQeyiorBREFBU/6kUFqdraD+t2/f2TZ7KZmSTv17y6LPODP0mePEnmyWQyeWd3rqenp2dNsry8vAu9ZMVVA9f0GtpkxaHcZGkROnyU5Af0tDOsLh5CF7nG131xSuhId/YGEl+YedXANS35S3O8YeYsA0uz0Mllkg2+NHduMBjobrfA7yDJLl9y3EB/Ia2ijTIYF1FlU/16dA2VWGTcjy1fg3Gvk9zsSwQElh0fOjuJYs5bVQ3sX/rqmfKbDVcDe7X6Kq5aVZLibNBYdyPeEJaYwDCbFRrFsjMldfdSY5fucnbTop9bSJq73zrsj1v+f4dred+yI5OdCTq7kyS1hDWj80xiWDr4NmdZO3oX3G2pI75zDLmZ5IIvtdiH60eWHw061O6cQ8/NDnN1AUdcMfPU0NcvvkuPmWW/w1uyvGiuLUrv4UuW5thjaZPivjAm8QYUr6J3LM0x2aTbbDU5j7aZi8ObA13e4QX0N9KKesbMAWw5Rj551aDhr7694xrSqaaFrw50FvAoMN5eP+wKVjU+tN2KdGxrzW6MBon4TwOuYNzv/fDLO800PXT2IbqMvjGTQ6NEhIDJ34MuIbUp6Q+kt0INbBuRNi5N+oNmdlDWo3UFnTBTd9Cpls1VFHPaqksBX/emkdBRNEB5B6q1tyrVfeotAfm9bdVFir+W6OQR9DvZT5AOIjHzlpZYZ+koxAHplfcdik918bPZvBb5fUA7rZQHvGkMaDSPvkU51LFe/A5vCsR3eB+Kf83k0C78pLXRMm6ej8V+1ymQX4+0nHPoeV4w9zw4bUbn1CLDP+gJcw/4qsDEmxZtd6LUY/CKudTA/h4qPTZfm2sbKg+g1MwK3aWDKHmocB4rTBQw7fTM6tXX5HlzyYLPGe+aRDEtmqtz3oRSA1UsorB8U3i3QLykb0c/I+2ykh6F1rscm65Bq6fJc+YyEviXVqcegQU5HXPFNnodbLe+inj3QBywTkkpwkmNfGs3Nl42l7GgnU5nmtwUx+Vwm88n+Qrpi0QR7xqIA85xr9Vrz5hoGaegnfrTisrhv9aQeQqVdtMzzjGD+VTEAT+LmvvCIavLLeOwG48D7U775kk0zgFzXQHjKVedRhd+zFxr+OrA0E0LH+3GqWBbn4Gx6a61TmECu5bvUZTbbGX/zNzz4FT6RqUT133m6vDmQDFg6hVsahm3NihsOvhUwZw1s4PyYyg1aRWKYYu5DwfnW9FPapkhfOqxcsWwgFMHhuRujD33AWC/tyT5ExXfKkVo/Ca6oJ4a6OjnsHJFNmDqBt6lxgtW3YK62rhmlr36ZRSjN0Ltk9BU0NlhFL8+HraqcQLWsTF+ZWQ/xQjqcwHf7y0OLevZ/UWEzl9Ftd+cGjVi2JLegu5CQ79K4JMMWFDcjt5Ck33dmAZdTEQx4HGgr2zAk1L8ebgW6QNe66z2gJcs7YxOPponNpTPLZ2W3ZY64j+1TMqsAp4JXQTcP8MTkv921B0/WjoVnSxpwap+lyT+l4cuOctqPmL5np6enp41ytzcv4ZsVaON0NKJAAAAAElFTkSuQmCC

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
