### ISSUE TITLE
[Request] 前程无忧51job

### ISSUE THREAD

**Issue by LamKwong-99** [BetterAndroid/android-notification-icon-project#243]
### APP 名称

前程无忧51job

### APP 包名

com.job.android

### 通知图标颜色 (HEX)

#fffd6905

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

小米推送

### 通知单色图标适配素材 (大小 50x50~72x72)

iVBORw0KGgoAAAANSUhEUgAAADoAAAA6CAYAAADhu0ooAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAvWSURBVGhD7VoLcFTVGc6+d7ObzTtBiAmpUAJCzWjR+kiQ1liQjtW2QBHUqZMWVGilMFEomKozTGkHnDqWjo9aUKuIxQfyMAkGI6AoyCtIMISYB3ksIfvKPu7d+9j+3829djfZZbKbXWpn/Gb+Off8595z/tf5z2M35Vt8i/9PqOQykVD6VMslIMplkAjtQ8cFP7RMOBKtKJTThJToH8JDUUF+BpR3lHa04R2FEo5Qq48W6EtLpCcyr1ixovDMF43z+/ps1V1dnZWlpaVm4huITGivqqoqPHHixE+bm5vmHz9+fKbchu9hhG8s4BkImUqUW1BQMJHx+5qDIeADgbbdu3fPoPYr7r77J9e4HP175SYJAZY5fuyzz6ZTOwyV6EhLGCAYBMwkKn7v3Xd/J8sfBoejv5baJ39YX79WZoVB4Pme3NxcC70Do6HPUBoVEh26OiKjKdU4TuIMgcVivZ4Ka05u7pRBTjjUGs2Y997aVkqP6AeGQzijVEI6boUTpSgEQF8QRuf3MdGypzY9Pd1CjZivEWGyZl1FBaaAZV11deH2rVuvrq6uzqe6MocT6ZyYgcEh/Fii0i1btlTL0RgGnud9RUVFcxpPHt8ps4ahoaFhMfVRfPTokRUUynaJKYp8gGHqX3rpb1dSG7wds2cTaR14UfKkSEA5FJBZp1ZrBDG6oB6XyzBr1qyiqVOvXkWhjDlPaqk0OoNh5v33/Xr/3Llz4e2Y5U6UoqGhGiTrc/JzGFQqlXrMmFyEYFQ4XS7tTdOnT9DpjNky62uoNbrCx1evvhqPg5yRIxkeFV0uu1/iDAG5UW21ZiL0ooJlWe2V48dHTGYEspUqDaVMI0YiFQUkZVvOtjoHq0NAIZiVlXFJj3o8nqDJZIqWrIJ2u91D5Tdijgbbz5+HMMMAd5gsVmTOqHC7Haxer49oDJri3Mljh/rwOMgZOZISuo6+PhZSSdxwqDSaS4854BzgLGnmiB6lLv3PPLfZrlTlckRISugKKhWtCCI/yPovyKEpBoNBowoGo4Zed3e3PzMzM0OuhoE6ZZqbm9FvTEoCSVGUlgheEHhmkBUGUlBzyTF5UQyajKkRPcpzXC8V0hgSIwaMRlEl8yneUQQI9jsvBjiO80ncIdDpdGryZ1RBbTZbQKvXR8zMZIRuKmJWEohVUSiFbR4SirIfHboXDTIehjY1QiSPpmgQv9FFDTrcDs5o0GMJGQYKXRaFTDEhFkXxrqKgdKa87rrrstasWTN2+ZIleVSHwtJZ0sMwoiCKETcNGVkZ2NlEBHZOHCeqzWZzuswKA8exF6hIqkfxHpSAMpZp0ybmtpw9u/LgwQO1Tz75RNPGTZva/X5fzdatr+LkISkrkFQohyIvJ4c29dGSER3VBCGFlpeIc5Tx+9upSJpHIRTeg5LmsWPHZu+t27/hqgkTVhsMxqm0qzNgI2A0mm6YN3fBzicef3wSvhnweiJuGjIy060UgxEFpTCgaSimaLRajDUMgQDvoiJpHlXmJRZxy7ZtWxfm5effhYahUKnVuoeXPbyaHjU+n989yA1HWlq6iRJrZEVpSTKbTDqaxhHlYhkv+kyqRzE3JUWnlEyZA2Y0ZGZmly5csKAoQJBZYaATiRTakUBLEpufl2fQarQRd0Z9F2zK8hIzYvEowsmQmpr6HTCjgRTRP/pY1XyOC0QUSKumsIwiKiWwgMli0Wl1WiS7oQie7+3pRzlYjQ0jUTQUagqviJ4KxbTvlc6eXDL5B3I1DDk5Ofl6Q+S9rMjxol6v1dKRdZjXKSELIjt8t5VIIGyxrhUQXXuq8cR2LANDEWBp9fR6nXI1LoiiIFA2/0SuhoEWZsdTTz2FaxZEVpSsPTrAugglrJUlRLecaWraE2BZj9cz0Ody2Dv31tX8g/g/Jpq9du0fHiN5eVm+hIHn+Y6CgoIsGuOS59nRANZD51jEcWeDtXLmggXzF1NuaKac44UgHs9AV2XlrxZR26zPjxyOeicUL1jGd1KWARGWNIR6dbLRaCxva23dL8vwNU41Nr5O7T+q2bXrRZmVMDgcjpepb0yhuBQdaTJCplN+PxGXL19eVFRcfDMawoB9LCEjK8sq1ROGoNjf23WAHkJ/v4kJsSgKJfC+uqzsZszVYQnBZNRnV1T8MG9SSUnEjBsvvF7vxxMmT91Oj8qPUUkDFETo4iJ52of19X+VIyoSaN+TWHx5+vRyGhfzE7kirow7Uo8CX3uUNqQSIwriEuRScHvdnVRgDcXASQ9dpQx2tn9lG6xeHnS1fwVFRxW2I1UUXlKSEf/cC883RroTSgZoF+H/5PBxGDapc1MBFMWOBAv2RKKbXS5XhzyFkgqGYY6WlJTg1n5UG4VYQhcWxa0BDtTMy5tf+juVSUeAYdrOnDmDceOam/EARjESKVvB8s6OtkOy4ZOGtnPnfk9j4cYh6vFuJBipRwFYFHMUl15eooGHHl620e/zXqTnpID0DHxQV/cBPcadbRWMxkqq5uZmVhD55hnlM26l83TE64/RwO1yvXtTWRm2fjgawsiXDUhKMI70pwwiJKbrH3nkt7+hg7a0uU8UOI7tWbp0KaYIwjapG/logLIYGAJgvk4g+v7s22//ha2394Qs56jAsWxPQ33dPOoXP03gkB7LFEsoMDDSPZSFZ3G9guNb2ZtvvrHO6XB8JcscM9xO+6Hnn990G/WVQ4RtJyIIxv2fAYNDWYQx1lfcQOCq81qiW17ZsmXt+Y6Og3RgZmQdooJh/H19tt66D+reX0rfjieCkug37r3tUIy2E3wPiyOUIRSWn1AyZKalGZYuW3bV1GuuGZdmNltMJoMeP7b5WcHn6O+379yxo+mi0zlQW1uL7I1fykFYq7F2Juy0Eo+i+Eb5LrREOENpKIwMDMIzjAA+2pX3ITwI20goFEpQTiFlWRn1ZkEZeKRQFFKUQglAEAiltCvKoa7wQpWFElAytFSUUa1bt86s1+uDK1euxIV1qMKXDRAUXkISyjx35osHujrbH7X1dFX199lWPrN+PeYpMmXW4UMHKsB/8dlni6iOKxDwc7vPd6xxu13/XF9djXcxD5FwkFlR4r0sOn/eJwq8237RVkV1TAEYTjHSZQG8AuGwyS5iWaZVFISAwHNugedd2/615cbsbNM4v8/3mZxngp1tbffQu7haQcK6wudxf4p7TfJWMdXxPyIYQDIOEQ72hQc++mgJvu3p6voL1TEWDIupoERJzICVYgEGwWC68htvzAoGU1K7e7p37Nz13rJ58++64f7KJZ39/X79kcOfvtHeem4zPmA4Fu+DIKiJzuzSmO3t7ZYNG9ZPcrucr5Gx2shYTTZb7wZqMg+43fBuSkZGxh2CwLfwfOCUvc/2ALEui6IYQCGN0WjU47CYn5d/25133r359df+vefBykqsqeqyGTP3ON0D+C0T/xuSDCOTXhAFNSab3W63LLpn0eo0a/rsj/c3bLT12g7l5eUvrK/f+0s/45Nu8gMcpz64/8DTQTFozcjO/dOqVasQ2klXNAy1+/YNFI0r+NmUSZPubPmy6VWd3jB+8UMPzaKmsMTBB1iMoSiqowaab8EgGcBgTc8spXV2oGL2nNrtb7+9A+8XFhROIx6Mk3K2peVg+a237nE4HEdUKpW1oqJiDLEvm6LSsrDp6aeLd9e+//M/b9w43WrNGENTKuDz+XqoDUtEQKvR4L0UURClCDjQ0FBx4vPD91rMlmJSsuvkyaNel8vZqtGoTTveeWtOeXnZTfResLe35xwdEKRvvztx4syamj13pJrNxRTCvceOHUMWjkvRWIABkP3wx+G8fXtr7qd5NUDRKwZYpqOzvf2PxEfoYv9bcPrUySo+wFxo2LdvPtULXY7+WjKGyDJMx54d7+AfnFMXV1ZWXLD11tAcZXku4GxtaXlBp9OVbn1l84MBv58Sua2B8hZH/Z/78nTjvfRN3Bv8WKwjeYYIIYiUj4SBn8XUtI2Rbh2IlHskvAOBlBDGd5jXGoZhlHUR0aQsGwB4IMWgEp8G4qhj9I0dE0oc2SSPjxwpKf8BiSGSqtEUPCwAAAAASUVORK5CYII=

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
你要不 PR 吧

**Comment by LamKwong-99** [comment]
我试一试，还不太会用

**Comment by fankes** [comment]
@NekoMua
