### ISSUE TITLE
[Request] 微众银行

### ISSUE THREAD

**Issue by LamKwong-99** [BetterAndroid/android-notification-icon-project#244]
### APP 名称

微众银行

### APP 包名

com.webank.wemoney

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

小米推送

### 通知单色图标适配素材 (大小 50x50~72x72)

iVBORw0KGgoAAAANSUhEUgAAADcAAAA3CAYAAACo29JGAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAQoSURBVGhD1Zo/aBRBFMb3zuRMSIJRFKNEsfDQBCOCghZpg7YWFhYBtbHSTlS0E4uAhaWFhaCgYC8I/mksYiNYCKKCUYwkeErEy+W4Pzm/72Y2JHczu7N3ud2XH3zO3EWy++XNzJt5uykvAWq1WhcayqeSSqUqur9uxGIOZvrRDGtth65C26AMRJag39AUlIN+UDBcRCsPGOqBDkGvoVmoAFWhMCrQIvSxXC5PoB3SvzJ5cDNdxWIxi3YaWoLagX+MeWgc6tGXSAbcwGClUjmNNg+tJ4zmJMQhHTupfD6/Exe/AC1DneIrdFBfMx5wwd3VavUS2k4a85ktFAp79KU7Cy42BGOX1XVj4z00qG/BSlq3LYEL9MPYRDqdvqu/iosx6ITq2mkrz8HcMTRvoM31L+LlFzSKXMi8aKTlyMHYAJpHUBLGCFfOcdU1EzlyMMVtE3POEegV1A0lxRyURfTy6uNanCJHQ9AwdAofp6EP0EsoSWNkK7RPdZtxHZbMLW+hZ9BRaC/k7wuThFPigOo24zQsETFG67j6JI4v0IjpVOEaOe7Wa6orDp44Vh+fVnA1x+X+IrRc/ySLXm9x0ZjQncwh5MwpT6GT0E+oCkmhz8tkjIuKa+RocAF6gS4XlPn6lzLo8rq72zO3Qqm0A//yFC0JnuybiGQOq2Y/hsBjdJM9ODZjzLdRI7cfyqquKFiDacLZHHcpaO5BEpJ3I3d0u4YokWPlalR1RcH8+1d11xLF3AjEhCkN7kyMxx4ncxiSLK/dh2Kpc0bkH8Q6ZxOh5vRc46l3V/0LefDY03LkmCAfQBKjRv6YNs0k0ByixnzG0/aW+hfy4GLCTb2RsMgxrx1WXZEwYhyWRqzm9FzjItJb/0ImfFAS3RzgChlvdTc6fDLUUvWLxljhksx1LCbWx1xGc3pIcksTNieThPNtRnXN2G6eNUEWgSTD5N2SOc63PtUVyzfIOt9IUOSMRRchsJZzxZa8fWzmuEGWuiMhBYglvUAkLxhBcDha85vPRjU3E5QCfGzmAsdywnC+3VbdYGzmGHZJtcnVlKHQIUls5pg/mEckUoIWVDeYoMh9Ul1xcFg6TRujOZ0/zkNccjcstsiRz9A71d2YWM3p6E1CPFZIgtVlpypcUORokAvLWUjSoysenp3OmcYtlj7y8JkXH+o/hOS8OadgKhjDH7+ljTMrXueg55A0Y4QP+kPvy2aOVa9bUOCwTZCbUGDUiPHmc7kcz0pnINbgpexUOO+5sWCKeoIhGbpLsR5r9Lxj6DlE2d6AWL/khKb4c18+m3TbLvyDcrXmVouPp75D1yAec+ZgzOn14MhnNl2o5WKDtjTgeRka9g367y/7v9d/A4L/37Z8czvFiPjP2FhkZVS4xeKbQXxc7bTdaiSWA6keBasj3EgH3k73vP8/BSKUO2rx/wAAAABJRU5ErkJggg==

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by NekoMua** [comment]
老哥你要不试着直接提交PR

**Comment by LamKwong-99** [comment]
hhh,我学学怎么直接提交PR

**Comment by NekoMua** [comment]
现在要先复刻（之前不用，因为文件比较小），在自己复刻的项目提交文件，然后在主项目跨复刻比较就行
![image](https://user-images.githubusercontent.com/59407295/217160448-056ec957-0276-4c18-b9e0-43acad467bba.png)

**Comment by LamKwong-99** [comment]
ok,我下次试一试
