### ISSUE TITLE
[Request] 浦大喜奔

### ISSUE THREAD

**Issue by vay1314** [BetterAndroid/android-notification-icon-project#251]
### APP 名称

浦大喜奔

### APP 包名

com.spdbccc.app

### 下载渠道、来源地址链接

酷安
https://www.coolapk.com/apk/com.spdbccc.app

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
