### ISSUE TITLE
[Request] 流量监控

### ISSUE THREAD

**Issue by 7883628** [BetterAndroid/android-notification-icon-project#253]
### APP 名称

流量监控

### APP 包名

com.unexpected.traffic

### 下载渠道、来源地址链接

【超级流量监控 1.3… 链接:https://pan.baidu.com/s/1cz5RdNbs3-Zrh97SXV-PLQ  提取码:934z

### 简单描述适配的通知图标使用场景

状态栏常驻查看流量使用情况，请帮忙适配，谢谢。

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
