### ISSUE TITLE
[Request] 我的OPPO

### ISSUE THREAD

**Issue by mophisgy** [BetterAndroid/android-notification-icon-project#256]
### APP 名称

我的OPPO

### APP 包名

com.oplus.vip

### 下载渠道、来源地址链接

系统自带

### 简单描述适配的通知图标使用场景

OPPO推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
为什么还有一个不一样包名的，草了

**Comment by mophisgy** [comment]
vip牛逼



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月9日(周四) 中午12:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fankes/AndroidNotifyIconAdapt] [通知图标优化适配反馈] (Issue #256)




 
为什么还有一个不一样包名的，草了

**Comment by fankes** [comment]
加上了

**Comment by mophisgy** [comment]
谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月9日(周四) 中午12:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fankes/AndroidNotifyIconAdapt] [通知图标优化适配反馈] (Issue #256)




 
加上了
