### ISSUE TITLE
[Request] 请求适配MissLee(李跳跳)

### ISSUE THREAD

**Issue by li0625** [BetterAndroid/android-notification-icon-project#258]
### APP 名称

MissLee

### APP 包名

cn.litiaotiao.app

### 通知图标颜色 (HEX)

#FF167F57

### 下载渠道、来源地址链接

https://wwe.lanzouw.com/b01v0g3wj 密码1233 选择李跳跳2.01

### 简单描述适配的通知图标使用场景

软件打开前台服务(常驻通知栏) 状态栏显示彩色图标
触发方法打开软件→更多→多拉百宝箱→前台服务
![IMG_20230210_002154](https://user-images.githubusercontent.com/104386128/217874139-d7ccaba0-e6d2-4a92-ae80-11bd0657ca6a.jpg)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
下载 [这个模块](https://github.com/fankes/MIUINativeNotifyIcon/files/8147189/Miui.12.Notification.Importance_1.2.zip) 然后激活，然后长按李跳跳的通知，进入通知渠道中，将优先级设置为最小化，即可隐藏状态栏上的图标，李跳跳的图标没有人画，没有合适的图标且它不应该显示，所以不能适配。

**Comment by fankes** [comment]
方法二：在模块中开启使用占位符图标修补通知图标功能。
