### ISSUE TITLE
[Request] 请添加斑点猫app

### ISSUE THREAD

**Issue by zhoupu210** [BetterAndroid/android-notification-icon-project#259]
### APP 名称

斑点猫

### APP 包名

com.wondershare.spotmau

### 下载渠道、来源地址链接

http://cdn-static.1719.cn/app/202009/1817/8go0ghwjdptx.apk

### 简单描述适配的通知图标使用场景

在MIUI13和14系统下都是彩色的，不变色的。

### 通知单色图标适配素材 (大小 50x50~72x72)

不会提取图标啊。

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
