### ISSUE TITLE
[Request] 请求适配易博通

### ISSUE THREAD

**Issue by 9iulii** [BetterAndroid/android-notification-icon-project#260]
### APP 名称

易博通

### APP 包名

com.multibyte.esender.jiedian

### 下载渠道、来源地址链接

https://play.google.com/store/apps/details?id=com.multibyte.esender.jiedian

### 简单描述适配的通知图标使用场景

虚拟号码运营商软件，收到短信及来电时未能规范通知图标，仍为彩色

### 通知单色图标适配素材 (大小 50x50~72x72)

![ic_launcher](https://user-images.githubusercontent.com/24207860/218315392-f1f027b4-a12f-4a9c-8d62-fa5ba854a3f7.png)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
