### ISSUE TITLE
[Request] 千牛

### ISSUE THREAD

**Issue by ElainaFanBoy** [BetterAndroid/android-notification-icon-project#265]
### APP 名称

千牛

### APP 包名

com.taobao.qianniu

### 下载渠道、来源地址链接

https://work.taobao.com/

### 简单描述适配的通知图标使用场景

默认彩色，始终无变化

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
