### ISSUE TITLE
[Request] WeTv 通知图标适配请求

### ISSUE THREAD

**Issue by Origin0915** [BetterAndroid/android-notification-icon-project#270]
### APP 名称

WeTv

### APP 包名

com.tencent.qqlivei18n

### 下载渠道、来源地址链接

google应用商店

### 简单描述适配的通知图标使用场景

小米推送，任何时候都是彩色的，大概是还没适配的原因吧？这个软件是腾讯视频的国际版，叫做wetv，还请能适配一下。

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by Origin0915** [comment]
> @NekoMua

thanks
