### ISSUE TITLE
[Request] 倍思

### ISSUE THREAD

**Issue by cbwutuobang** [BetterAndroid/android-notification-icon-project#271]
### APP 名称

倍思

### APP 包名

com.baseus.intelligent

### 下载渠道、来源地址链接

https://sj.qq.com/appdetail/com.baseus.intelligent

### 简单描述适配的通知图标使用场景

常驻通知栏的通知一直是白色图标
![Screenshot_2023-02-21-09-46-33-362_com microsoft emmx](https://user-images.githubusercontent.com/33741562/220226802-65276284-27d9-407a-8694-90f09f174069.jpg)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
