### ISSUE TITLE
[Request] 美团外卖商家版

### ISSUE THREAD

**Issue by toraidl** [BetterAndroid/android-notification-icon-project#272]
### APP 名称

美团外卖商家版

### APP 包名

com.sankuai.meituan.meituanwaimaibusiness

### 下载渠道、来源地址链接

https://e.waimai.meituan.com/file/app/download

### 简单描述适配的通知图标使用场景

该app通常会常驻在任务栏。
![669bde21ab397cec6c95ffa1aaa59749](https://user-images.githubusercontent.com/3390079/220813365-d74c7576-2a84-4441-9768-acb55953791e.jpg)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
