### ISSUE TITLE
[Request] 饿了么零售商家版

### ISSUE THREAD

**Issue by toraidl** [BetterAndroid/android-notification-icon-project#273]
### APP 名称

饿了么零售商家版

### APP 包名

com.baidu.lbs.xinlingshou

### 下载渠道、来源地址链接

https://shop.ele.me/apps/mobile/?t=ls-m#

### 简单描述适配的通知图标使用场景

该app通常会常驻在任务栏。
![669bde21ab397cec6c95ffa1aaa59749](https://user-images.githubusercontent.com/3390079/220813844-899e8ac8-7633-4b11-8282-955fb2697683.jpg)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
