### ISSUE TITLE
[Request] 十八腔

### ISSUE THREAD

**Issue by conpin** [BetterAndroid/android-notification-icon-project#275]
### APP 名称

十八腔

### APP 包名

com.shibaqiang.forum

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.shibaqiang.forum

### 简单描述适配的通知图标使用场景

打开APP通知开关后，推送的通知图标为彩色，通过小米推送也是彩色

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
