### ISSUE TITLE
[Request] 请求适配软件U净的通知图标

### ISSUE THREAD

**Issue by Sky3051** [BetterAndroid/android-notification-icon-project#277]
### APP 名称

U净

### APP 包名

com.midea.vm.washer

### 下载渠道、来源地址链接

酷安

### 简单描述适配的通知图标使用场景

完成取水等生活操作的订单后，该软件会弹出相关的订单消息
![Uploading Screenshot_2023-02-28-08-36-01-534_com.xiaomi.xmsf.jpg…]()

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
请补全截图：Uploading Screenshot_2023-02-28-08-36-01-534_com.xiaomi.xmsf.jpg…

**Comment by fankes** [comment]
@NekoMua

**Comment by Sky3051** [comment]
不好意思，没注意图片没有上传成功
非常抱歉不知道怎么在原来的信息上编辑添加图片，所以在新的comment上添加，谢谢大佬
![Screenshot_2023-02-28-08-36-01-534_com xiaomi xmsf](https://user-images.githubusercontent.com/11015769/221728389-c7fba28e-08a8-49fd-a325-f6cebd47661f.jpg)

**Comment by fankes** [comment]
@NekoMua 另附：开启全部替换

**Comment by Sky3051** [comment]
🥲这也是俺觉得奇怪的地方，看这图标应该是有适配的，打开全部替换就好了，但是在您们的适配名单中没有找到该软件
