### ISSUE TITLE
[Request] 36氪

### ISSUE THREAD

**Issue by conpin** [BetterAndroid/android-notification-icon-project#281]
### APP 名称

36氪

### APP 包名

com.android36kr.app

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.android36kr.app

### 简单描述适配的通知图标使用场景

推送通知的图标只有彩色的，和APP图标一样。希望可以适配一下，感谢！

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
