### ISSUE TITLE
[Request] 马蜂窝

### ISSUE THREAD

**Issue by conpin** [BetterAndroid/android-notification-icon-project#282]
### APP 名称

马蜂窝

### APP 包名

com.mfw.roadbook

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.mfw.roadbook

### 简单描述适配的通知图标使用场景

推送通知图标只有彩色的，和APP一样。感谢适配一下！

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
