### ISSUE TITLE
[Request] 1TS 请求适配

### ISSUE THREAD

**Issue by Origin0915** [BetterAndroid/android-notification-icon-project#284]
### APP 名称

1TS

### APP 包名

com.unexpected.ts

### 下载渠道、来源地址链接

https://wwqs.lanzoub.com/ipMZm0pht4fg

### 简单描述适配的通知图标使用场景

这是联通的流量监控，如果开着的话就会一直占用通知栏第一个的位置，而且这个软件的图标本身就是黑白配色的，所以还请适配一下

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by Origin0915** [comment]
谢谢谢

**Comment by fankes** [comment]
@NekoMua
