### ISSUE TITLE
[Request] tesla

### ISSUE THREAD

**Issue by conpin** [BetterAndroid/android-notification-icon-project#285]
### APP 名称

tesla

### APP 包名

com.teslamotors.tesla

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.teslamotors.tesla

### 简单描述适配的通知图标使用场景

mi push和hms push图标都为彩色app图标，帮忙适配一下，谢谢

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
