### ISSUE TITLE
[Request] 皮皮搞笑 请求适配

### ISSUE THREAD

**Issue by Duanchuyang** [BetterAndroid/android-notification-icon-project#286]
### APP 名称

皮皮搞笑

### APP 包名

cn.xiaochuankeji.zuiyouLite

### 下载渠道、来源地址链接

http://www.pipigx.com

### 简单描述适配的通知图标使用场景

彩色图标，没有黑白

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by Duanchuyang** [comment]
请求适配

**Comment by fankes** [comment]
@NekoMua
