### ISSUE TITLE
[Request] My BMW

### ISSUE THREAD

**Issue by junjiang228** [BetterAndroid/android-notification-icon-project#289]
### APP 名称

My BMW

### APP 包名

de.bmw.connected.mobile20.cn

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

这个App目前没有适配，一直显示为彩色。

### 通知单色图标适配素材 (大小 50x50~72x72)

![R1](https://user-images.githubusercontent.com/60344149/224007722-876e23ec-d823-4899-95a5-1cfe2861a29f.png)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by Origin0915** [comment]
尊敬的宝马车车主你好😂

**Comment by junjiang228** [comment]
等到花儿都谢了😂

**Comment by NekoMua** [comment]
> 等到花儿都谢了😂

别急，我前些阵子生病了，没办法

**Comment by fankes** [comment]
> > 等到花儿都谢了😂
> 
> 别急，我前些阵子生病了，没办法

老哥注意身体

**Comment by junjiang228** [comment]
> > 等到花儿都谢了😂
> 
> 别急，我前些阵子生病了，没办法

辛苦了！
