### ISSUE TITLE
[Request] 比亚迪汽车

### ISSUE THREAD

**Issue by conpin** [BetterAndroid/android-notification-icon-project#292]
### APP 名称

比亚迪汽车

### APP 包名

com.byd.aeri.caranywhere

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.byd.aeri.caranywhere

### 简单描述适配的通知图标使用场景

mipush推送的通知图标为彩色，未适配。帮忙适配一下，谢谢

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
