### ISSUE TITLE
[Request] 专注清单

### ISSUE THREAD

**Issue by FloatingClouds02** [BetterAndroid/android-notification-icon-project#293]
### APP 名称

专注清单

### APP 包名

com.superelement.pomodoro

### 下载渠道、来源地址链接

Google Play 商店

### 简单描述适配的通知图标使用场景

小米推送是彩色图标，希望能适配一下，谢谢！

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
