### ISSUE TITLE
[Request] 淘特

### ISSUE THREAD

**Issue by jeffreyleeeee** [BetterAndroid/android-notification-icon-project#294]
### APP 名称

淘特

### APP 包名

com.taobao.litetao

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

小米推送和HMS推送未适配

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
