### ISSUE TITLE
[Request] 请求适配小米系统设置

### ISSUE THREAD

**Issue by Hehonge-onli** [BetterAndroid/android-notification-icon-project#296]
### APP 名称

设置

### APP 包名

com.android.settings

### 下载渠道、来源地址链接

MIUI系统自带

### 简单描述适配的通知图标使用场景

单色图标没有，有的通知黑白有的通知彩色图标
![IMG_20230318_195925](https://user-images.githubusercontent.com/110095079/226114823-dc1d1df2-3743-4223-8bf4-2ab9f978b1d2.jpg)
![IMG_20230318_232159](https://user-images.githubusercontent.com/110095079/226114868-c582bf67-7ced-400a-bb1c-1cd85da9c27d.jpg)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua 加到 MIUI 分类，开全部替换
