### ISSUE TITLE
[Request] 请求适配中铁e通

### ISSUE THREAD

**Issue by KIITTID** [BetterAndroid/android-notification-icon-project#300]
### APP 名称

中铁e通

### APP 包名

cn.crec.wxwork

### 通知图标颜色 (HEX)

#FF0168D3

### 下载渠道、来源地址链接

获取地址： http://app.xiaomi.com/detail/1502085 来自@小米应用商店

### 简单描述适配的通知图标使用场景

此应用通知均为默认的应用图标，很是违和。

### 通知单色图标适配素材 (大小 50x50~72x72)

[72](https://i.postimg.cc/Gtz6Q4MB/CREGC.png)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
