### ISSUE TITLE
[Request] 汽水音乐 请求适配

### ISSUE THREAD

**Issue by Origin0915** [BetterAndroid/android-notification-icon-project#301]
### APP 名称

汽水音乐

### APP 包名

com.luna.music

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.luna.music

### 简单描述适配的通知图标使用场景

未适配

### 通知单色图标适配素材 (大小 50x50~72x72)

![mmexport1679718866727](https://user-images.githubusercontent.com/79388003/227696242-c985017a-c076-4e1b-b3c7-8807e92024a7.jpg)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by Origin0915** [comment]
这个素材瞎做的😂

**Comment by fankes** [comment]
@NekoMua

**Comment by Origin0915** [comment]
@NekoMua
