### ISSUE TITLE
[Request] 北京银行图标适配

### ISSUE THREAD

**Issue by TENGERZ** [BetterAndroid/android-notification-icon-project#302]
### APP 名称

北京银行

### APP 包名

com.bankofbeijing.mobilebanking

### 下载渠道、来源地址链接

一加应用商店

### 简单描述适配的通知图标使用场景

HMS推送
![Screenshot_2023-03-27-12-03-55-01_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/36339026/227838386-f27d3607-4cb2-4962-bdeb-6092c9b65b49.jpg)
![Screenshot_2023-03-27-12-03-49-49_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/36339026/227838395-e287b601-b3ce-43d2-bef4-28ba6094e775.jpg)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
