### ISSUE TITLE
[Request] 发现精彩

### ISSUE THREAD

**Issue by conpin** [BetterAndroid/android-notification-icon-project#303]
### APP 名称

发现精彩

### APP 包名

com.cs_credit_bank

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.cs_credit_bank

### 简单描述适配的通知图标使用场景

hms推送的通知图标为彩色的APP本身图标，帮忙适配一下，谢谢

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by NekoMua** [comment]
> @NekoMua

这图标没特征，不知道怎么做图标😂

**Comment by conpin** [comment]
> > @NekoMua
> 
> 这图标没特征，不知道怎么做图标😂

用广发银行的LOGO怎么样？

**Comment by NekoMua** [comment]
> > > @NekoMua
> > 
> > 
> > 这图标没特征，不知道怎么做图标😂
> 
> 用广发银行的LOGO怎么样？

可以是可以，要不就用广发银行的吧，似乎简单点
