### ISSUE TITLE
[Request] 猫耳FM

### ISSUE THREAD

**Issue by lin4578** [BetterAndroid/android-notification-icon-project#307]
### APP 名称

猫耳FM

### APP 包名

cn.missevan

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/cn.missevan

### 简单描述适配的通知图标使用场景

小米推送的还是为app的图标。原图标就为黑白色的，会进行适配吗？如果可以的话麻烦了。
![Screenshot_2023-04-09-13-12-02-505_mark via-edit](https://user-images.githubusercontent.com/41137500/230755716-a77437a7-a78a-49fe-821a-58bf2dc2b151.jpg)

### 通知单色图标适配素材 (大小 50x50~72x72)

![1681017236932](https://user-images.githubusercontent.com/41137500/230755724-f894dde4-bf67-4c9d-b001-89d8c2a36bb5.png)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by NekoMua** [comment]
这咋长的那么像github
