### ISSUE TITLE
[Request] Color OS 自带录音未适配

### ISSUE THREAD

**Issue by noahhhi** [BetterAndroid/android-notification-icon-project#310]
### APP 名称

录音

### APP 包名

com.coloros.soundrecorder

### 下载渠道、来源地址链接

系统自带

### 简单描述适配的通知图标使用场景

使用录音

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua 提交到 OS/ColorOS 目录
