### ISSUE TITLE
[Request] 请求适配智行火车票12306抢票

### ISSUE THREAD

**Issue by KIITTID** [BetterAndroid/android-notification-icon-project#311]
### APP 名称

智行火车票12306抢票

### APP 包名

com.yipiao

### 通知图标颜色 (HEX)

#FF29A0FA

### 下载渠道、来源地址链接

 http://app.xiaomi.com/detail/9550

### 简单描述适配的通知图标使用场景

推送的默认通知图标就是app彩色

### 通知单色图标适配素材 (大小 50x50~72x72)

![智行火车票](https://user-images.githubusercontent.com/32213083/232661547-73742287-2eaf-49d2-b9f7-afc1e2eaa7ac.png)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
