### ISSUE TITLE
[Request] u校园。适配

### ISSUE THREAD

**Issue by xingyiliu615** [BetterAndroid/android-notification-icon-project#312]
### APP 名称

u校园

### APP 包名

cn.unipus.ucampus.student

### 通知图标颜色 (HEX)

#2B9DFD

### 下载渠道、来源地址链接

http://app.unipus.cn/u/apd.html

### 简单描述适配的通知图标使用场景

从app直接返回桌面，
app会通知正在后台运行，
此时会使用原图标 

### 通知单色图标适配素材 (大小 50x50~72x72)

https://www.bing.com/images/search?view=detailV2&ccid=AYou%2Bigh&id=34F6ECC210E1AD225F36BB8C47D9F77F8C99D848&thid=OIP.AYou-ighanNYMauDvXv-gQAAAA&mediaurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FR.018a2efa28216a735831ab83bd7bfe81%3Frik%3DSNiZjH%252f32UeMuw%26riu%3Dhttp%253a%252f%252fpic.2265.com%252fupload%252f2017-12%252f2017122890262944.png%26ehk%3D6Cegh5JrZjnIvN49XxkUqfsuvXYwKUj3jMotjfKhlH4%253d%26risl%3D%26pid%3DImgRaw%26r%3D0&exph=256&expw=256&q=u%e6%a0%a1%e5%9b%ad%e5%9b%be%e6%a0%87&simid=608045809126030010&form=IRPRST&ck=1167571A16289EC51052696520F4C952&selectedindex=8&qpvt=u%e6%a0%a1%e5%9b%ad%e5%9b%be%e6%a0%87&pc=U316&ajaxhist=0&ajaxserp=0&vt=1&sim=11

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
