### ISSUE TITLE
[Request] gofasting

### ISSUE THREAD

**Issue by TIYU54** [BetterAndroid/android-notification-icon-project#313]
### APP 名称

gofasting

### APP 包名

gofasting.fastingtracker.fasting.intermittentfasting

### 下载渠道、来源地址链接

谷歌商店

### 简单描述适配的通知图标使用场景

总是彩色

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
