### ISSUE TITLE
[Request] 请求适配崩坏：星穹铁道

### ISSUE THREAD

**Issue by Hehonge-onli** [BetterAndroid/android-notification-icon-project#314]
### APP 名称

崩坏：星穹铁道

### APP 包名

com.HoYoverse.hkrpgoversea

### 下载渠道、来源地址链接

Google Play store 

### 简单描述适配的通知图标使用场景

仅有彩色图标，还有这个请求的是国际服，国服或者其他渠道服，包名我不知道
![Screenshot_2023-04-23-12-41-55-844_com miui gallery-edit](https://user-images.githubusercontent.com/110095079/233820381-cf918fcd-f540-4e93-9763-ceb6a38d69b3.jpg)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
我猜有两个包名，后面再说
@NekoMua

**Comment by Origin0915** [comment]
国内的官服包名是这个
com.miHoYo.hkrpg
@fankes
