### ISSUE TITLE
[Request] Beats 适配请求

### ISSUE THREAD

**Issue by Jisu-Woniu** [BetterAndroid/android-notification-icon-project#315]
### APP 名称

Beats

### APP 包名

com.apple.bnd

### 通知图标颜色 (HEX)

#ed1c24

### 下载渠道、来源地址链接

Google Play 商店

### 简单描述适配的通知图标使用场景

连接耳机时的通知

![Screenshot_2023-04-24-11-39-31-908-edit_com miui home](https://user-images.githubusercontent.com/31986081/233895038-7195d41e-80c2-4356-8203-1dbc95ea51b1.jpg)

### 通知单色图标适配素材 (大小 50x50~72x72)

https://commons.wikimedia.org/wiki/File:Beats_Electronics_logo.svg

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
