### ISSUE TITLE
[Request] 知识星球 请求适配

### ISSUE THREAD

**Issue by zazzy00** [BetterAndroid/android-notification-icon-project#316]
### APP 名称

知识星球

### APP 包名

com.unnoo.quan

### 下载渠道、来源地址链接

https://sj.qq.com/appdetail/com.unnoo.quan

### 简单描述适配的通知图标使用场景

小米推送通知图标为彩色APP图标，请求适配一下，谢谢！

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
