### ISSUE TITLE
[Request] 百家号

### ISSUE THREAD

**Issue by heibaigame** [BetterAndroid/android-notification-icon-project#317]
### APP 名称

百家号

### APP 包名

com.baidu.baijia

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.baidu.baijia

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
