### ISSUE TITLE
[Request] 番茄TODO

### ISSUE THREAD

**Issue by xswl-yyds** [BetterAndroid/android-notification-icon-project#319]
### APP 名称

番茄TODO

### APP 包名

com.plan.kot32.tomatotime

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.plan.kot32.tomatotime

### 简单描述适配的通知图标使用场景

在后台运行或者计时的时候，状态栏通知图标是彩色的

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by xswl-yyds** [comment]
不好意思，我这边更新规则之后好像还是没有呢？在规则列表里面也没有搜到该软件，打扰了

**Comment by NekoMua** [comment]
> 不好意思，我这边更新规则之后好像还是没有呢？在规则列表里面也没有搜到该软件，打扰了

@fankes 我没做番茄TODO和星穹铁道的😂😂

**Comment by NekoMua** [comment]
> 不好意思，我这边更新规则之后好像还是没有呢？在规则列表里面也没有搜到该软件，打扰了

主要是番茄TODO的图标过于不规则，我不太好搞😂

**Comment by xswl-yyds** [comment]
> > 不好意思，我这边更新规则之后好像还是没有呢？在规则列表里面也没有搜到该软件，打扰了
> 
> 主要是番茄TODO的图标过于不规则，我不太好搞😂

哈哈哈😂好的，我还以为是我这边操作不对。还是非常感谢大佬，谢谢☺️

**Comment by NekoMua** [comment]
我去问了番茄ToDo的作者，本来想找那位作者大大要一个的，没想到没有，我只好网上找了一个![9DBB76BE0A98F5E2922EE3C04EC64156](https://github.com/fankes/AndroidNotifyIconAdapt/assets/59407295/dd5ff544-46ed-432a-838d-1262a9e00f53)


> > > 不好意思，我这边更新规则之后好像还是没有呢？在规则列表里面也没有搜到该软件，打扰了
> > 
> > 
> > 主要是番茄TODO的图标过于不规则，我不太好搞😂
> 
> 哈哈哈😂好的，我还以为是我这边操作不对。还是非常感谢大佬，谢谢☺️

我去问了番茄ToDo的作者，本来想找那位作者大大要一个的，没想到没有，我只好网上找了一个![9DBB76BE0A98F5E2922EE3C04EC64156](https://github.com/fankes/AndroidNotifyIconAdapt/assets/59407295/dd5ff544-46ed-432a-838d-1262a9e00f53)

**Comment by xswl-yyds** [comment]
> 我去问了番茄ToDo的作者，本来想找那位作者大大要一个的，没想到没有，我只好网上找了一个![9DBB76BE0A98F5E2922EE3C04EC64156](https://github.com/fankes/AndroidNotifyIconAdapt/assets/59407295/dd5ff544-46ed-432a-838d-1262a9e00f53)
> 
> 
> > > > 不好意思，我这边更新规则之后好像还是没有呢？在规则列表里面也没有搜到该软件，打扰了
> > > 
> > > 
> > > 主要是番茄TODO的图标过于不规则，我不太好搞😂
> > 
> > 哈哈哈😂好的，我还以为是我这边操作不对。还是非常感谢大佬，谢谢☺️
> 
> 我去问了番茄ToDo的作者，本来想找那位作者大大要一个的，没想到没有，我只好网上找了一个![9DBB76BE0A98F5E2922EE3C04EC64156](https://github.com/fankes/AndroidNotifyIconAdapt/assets/59407295/dd5ff544-46ed-432a-838d-1262a9e00f53)

啊！这个图片确实是不规则😂又适配了吗？实在是麻烦你了🙏

**Comment by NekoMua** [comment]
> > 我去问了番茄ToDo的作者，本来想找那位作者大大要一个的，没想到没有，我只好网上找了一个![9DBB76BE0A98F5E2922EE3C04EC64156](https://github.com/fankes/AndroidNotifyIconAdapt/assets/59407295/dd5ff544-46ed-432a-838d-1262a9e00f53)
> > 
> > 
> > > > > 不好意思，我这边更新规则之后好像还是没有呢？在规则列表里面也没有搜到该软件，打扰了
> > > > 
> > > > 
> > > > 主要是番茄TODO的图标过于不规则，我不太好搞😂
> > > 
> > > 哈哈哈😂好的，我还以为是我这边操作不对。还是非常感谢大佬，谢谢☺️
> > 
> > 我去问了番茄ToDo的作者，本来想找那位作者大大要一个的，没想到没有，我只好网上找了一个![9DBB76BE0A98F5E2922EE3C04EC64156](https://github.com/fankes/AndroidNotifyIconAdapt/assets/59407295/dd5ff544-46ed-432a-838d-1262a9e00f53)
> 
> 啊！这个图片确实是不规则😂又适配了吗？实在是麻烦你了🙏

提交PR了，等合并

**Comment by xswl-yyds** [comment]
> > > 我去问了番茄ToDo的作者，本来想找那位作者大大要一个的，没想到没有，我只好网上找了一个![9DBB76BE0A98F5E2922EE3C04EC64156](https://github.com/fankes/AndroidNotifyIconAdapt/assets/59407295/dd5ff544-46ed-432a-838d-1262a9e00f53)
> > > 
> > > 
> > > > > > 不好意思，我这边更新规则之后好像还是没有呢？在规则列表里面也没有搜到该软件，打扰了
> > > > > 
> > > > > 
> > > > > 主要是番茄TODO的图标过于不规则，我不太好搞😂
> > > > 
> > > > 哈哈哈😂好的，我还以为是我这边操作不对。还是非常感谢大佬，谢谢☺️
> > > 
> > > 我去问了番茄ToDo的作者，本来想找那位作者大大要一个的，没想到没有，我只好网上找了一个![9DBB76BE0A98F5E2922EE3C04EC64156](https://github.com/fankes/AndroidNotifyIconAdapt/assets/59407295/dd5ff544-46ed-432a-838d-1262a9e00f53)
> > 
> > 啊！这个图片确实是不规则😂又适配了吗？实在是麻烦你了🙏
> 
> 提交PR了，等合并

哇塞(￣∀￣)感谢感谢🙏

**Comment by fankes** [comment]
好的👌
