### ISSUE TITLE
[Request] 网易邮箱

### ISSUE THREAD

**Issue by xswl-yyds** [BetterAndroid/android-notification-icon-project#320]
### APP 名称

网易邮箱

### APP 包名

com.netease.mobimail

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.netease.mobimail

### 简单描述适配的通知图标使用场景

小米推送mipush的通知图标是彩色的

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
