### ISSUE TITLE
[Request] 多邻国

### ISSUE THREAD

**Issue by MuffinMannnnn** [BetterAndroid/android-notification-icon-project#325]
### APP 名称

多邻国

### APP 包名

com.duolingo

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by MuffinMannnnn** [comment]
好的，已收到你的来信，我会尽快回复！
