### ISSUE TITLE
[Request] 请求适配咪咕音乐

### ISSUE THREAD

**Issue by twoone-3** [BetterAndroid/android-notification-icon-project#329]
### APP 名称

咪咕音乐

### APP 包名

cmccwm.mobilemusic

### 下载渠道、来源地址链接

酷安搜索

### 简单描述适配的通知图标使用场景

在使用mipush推送咪咕音乐通知时会变成彩色
![Screenshot_2023-05-15-10-10-50-703_mark via](https://github.com/fankes/AndroidNotifyIconAdapt/assets/62778573/cb5a1c0d-9c6f-4a26-9660-0afe5f4e6423)

### 通知单色图标适配素材 (大小 50x50~72x72)

![1](https://github.com/fankes/AndroidNotifyIconAdapt/assets/62778573/4b537635-fe47-4ffc-9a1c-f3bbfcc27557)
![0](https://github.com/fankes/AndroidNotifyIconAdapt/assets/62778573/f2aca6ab-175f-4daf-b411-1b3a1c00a6d9)
只能找到这两个图片，从完美图标计划里面提取的

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
