### ISSUE TITLE
[Request] 飞常准业内版适配

### ISSUE THREAD

**Issue by 1889737514** [BetterAndroid/android-notification-icon-project#330]
### APP 名称

飞常准业内版

### APP 包名

com.feeyo.vz.pro.cdm

### 通知图标颜色 (HEX)

#498df6

### 下载渠道、来源地址链接

各大应用商店

### 简单描述适配的通知图标使用场景

应该未有原生单色图标
广播接收器可见有小米推送和HMS推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
