### ISSUE TITLE
[Request] 随申办市民云

### ISSUE THREAD

**Issue by Seperatic** [BetterAndroid/android-notification-icon-project#331]
### APP 名称

随申办市民云

### APP 包名

mobi.w3studio.apps.android.shsmy.phone

### 下载渠道、来源地址链接

http://m.eshimin.com/soft/SHService74_2.apk

### 简单描述适配的通知图标使用场景

 由应用进行任意通知，（大概率）未接入mipush

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
