### ISSUE TITLE
[Request] 工银商户之家

### ISSUE THREAD

**Issue by lirkang** [BetterAndroid/android-notification-icon-project#332]
### APP 名称

工银商户之家

### APP 包名

com.icbc.biz.elife

### 下载渠道、来源地址链接

OPPO应用商店

### 简单描述适配的通知图标使用场景

打开app的常驻通知

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
