### ISSUE TITLE
[Request] 剪映

### ISSUE THREAD

**Issue by lirkang** [BetterAndroid/android-notification-icon-project#338]
### APP 名称

剪映

### APP 包名

com.lemon.lv

### 下载渠道、来源地址链接

OPPO应用商店

### 简单描述适配的通知图标使用场景

OPPO消息推送图标是白块

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by lirkang** [comment]
已经好了

**Comment by fankes** [comment]
刚发现剪映已经重复提交了三遍，请勿重复提交已适配图标否则 spam 处理
