### ISSUE TITLE
[Request] 李跳跳

### ISSUE THREAD

**Issue by lirkang** [BetterAndroid/android-notification-icon-project#345]
### APP 名称

李跳跳

### APP 包名

cn.litiaotiao.app

### 下载渠道、来源地址链接

李跳跳公众号

### 简单描述适配的通知图标使用场景

前台保活通知

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
李跳跳不适配，请参考 #258
