### ISSUE TITLE
[Request] 游戏助手

### ISSUE THREAD

**Issue by lirkang** [BetterAndroid/android-notification-icon-project#346]
### APP 名称

游戏助手

### APP 包名

com.oplus.games

### 下载渠道、来源地址链接

coloros系统自带

### 简单描述适配的通知图标使用场景

打开游戏时游戏助手运行的通知

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua 加到 ColorOS 目录
