### ISSUE TITLE
[Request] welink，请帮忙适配，万分感谢

### ISSUE THREAD

**Issue by sien2023** [BetterAndroid/android-notification-icon-project#350]
### APP 名称

Welink

### APP 包名

com.huawei.welink

### 下载渠道、来源地址链接

https://www.huaweicloud.com/product/welink-download.html

### 简单描述适配的通知图标使用场景

HMS推送

### 通知单色图标适配素材 (大小 50x50~72x72)

![N3U](https://github.com/fankes/AndroidNotifyIconAdapt/assets/135495042/000038b6-efce-437f-a2cb-e038f62c5787)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
