### ISSUE TITLE
[Request] 请求适配迅游手游加速器图标

### ISSUE THREAD

**Issue by AnnAngela** [BetterAndroid/android-notification-icon-project#352]
### APP 名称

迅游手游加速器

### APP 包名

cn.wsds.gamemaster

### 下载渠道、来源地址链接

xunyou.mobi

### 简单描述适配的通知图标使用场景

加速手游时会有常驻通知提示正在加速中

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
