### ISSUE TITLE
[Request] 小寻

### ISSUE THREAD

**Issue by Grizzly-hash** [BetterAndroid/android-notification-icon-project#353]
### APP 名称

小寻

### APP 包名

com.xiaoxun.xun

### 下载渠道、来源地址链接

https://apps.imiwear.com/

### 简单描述适配的通知图标使用场景

这个APP的通知的图标一直都是彩色的，
在手表发送消息时，手表状态发生变化等都会触发推送。
![Screenshot_2023-06-06-23-45-36-399_com android se](https://github.com/fankes/AndroidNotifyIconAdapt/assets/57932246/8737f5d6-5eba-4735-be10-45a5830311fe)

### 通知单色图标适配素材 (大小 50x50~72x72)

单色图标没找到，自己P了一下，技术估计不太行hhhh
![小寻logo](https://github.com/fankes/AndroidNotifyIconAdapt/assets/57932246/fa138b24-82b9-41da-a934-b4d6e81e16e1)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
