### ISSUE TITLE
[Request] kindle请求适配

### ISSUE THREAD

**Issue by xswl-yyds** [BetterAndroid/android-notification-icon-project#354]
### APP 名称

kindle

### APP 包名

com.amazon.kindle

### 下载渠道、来源地址链接

https://play.google.com/store/apps/details?id=com.amazon.kindle

### 简单描述适配的通知图标使用场景

将手机电子书发送到kindle时，发送图标以及成功图标都是彩色的

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
