### ISSUE TITLE
[Request] welink图标显示偏小，请帮忙更新一下，谢谢大佬，谢谢

### ISSUE THREAD

**Issue by sien2023** [BetterAndroid/android-notification-icon-project#357]
### APP 名称

Welink

### APP 包名

com.huawei.welink

### 下载渠道、来源地址链接

https://www.huaweicloud.com/product/welink-download.html

### 简单描述适配的通知图标使用场景

HMS推送，库中已有，但是图标显示偏小，请帮忙更新，谢谢大佬

### 通知单色图标适配素材 (大小 50x50~72x72)

![未标题-1](https://github.com/fankes/AndroidNotifyIconAdapt/assets/135495042/ef27a7b7-7e1e-4bcd-a2d6-e8549df5cc4a)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by NekoMua** [comment]
这俩周学期末了，比较忙，等过这阵子再说吧
