### ISSUE TITLE
[Request] outlook

### ISSUE THREAD

**Issue by Anz-03** [BetterAndroid/android-notification-icon-project#359]
### APP 名称

outlook

### APP 包名

com.microsoft.office.outlook

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

outlook 小米商店版最近支持了小米推送，在小米推送的情况下，状态栏图标为彩色。
![Screenshot_2023-06-21-18-30-44-678_com miui securitycenter](https://github.com/fankes/AndroidNotifyIconAdapt/assets/106299500/af6759cc-0314-49d5-84a2-1334ee0ae113)

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
