### ISSUE TITLE
[Request] 光大银行

### ISSUE THREAD

**Issue by troublewind** [BetterAndroid/android-notification-icon-project#360]
### APP 名称

光大银行

### APP 包名

com.cebbank.mobile.cemb

### 通知图标颜色 (HEX)

#AF27DB

### 下载渠道、来源地址链接

https://app.xiaomi.com/details?id=com.cebbank.mobile.cemb

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
