### ISSUE TITLE
[Request] 小翼管家

### ISSUE THREAD

**Issue by troublewind** [BetterAndroid/android-notification-icon-project#361]
### APP 名称

小翼管家

### APP 包名

com.yueme.itv

### 通知图标颜色 (HEX)

#8ED223

### 下载渠道、来源地址链接

http://app.xiaomi.com/detail/578388

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
