### ISSUE TITLE
[Request] 孔夫子旧书网

### ISSUE THREAD

**Issue by anyin0** [BetterAndroid/android-notification-icon-project#362]
### APP 名称

孔夫子旧书网

### APP 包名

com.kongfz.app

### 下载渠道、来源地址链接

豌豆荚

### 简单描述适配的通知图标使用场景

状态栏图标为彩色

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
