### ISSUE TITLE
[Request] 爱企查

### ISSUE THREAD

**Issue by anyin0** [BetterAndroid/android-notification-icon-project#363]
### APP 名称

爱企查

### APP 包名

com.baidu.xin.aiqicha

### 下载渠道、来源地址链接

豌豆荚

### 简单描述适配的通知图标使用场景

状态栏图标为彩色

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
