### ISSUE TITLE
[Request] 网易云游戏

### ISSUE THREAD

**Issue by Mc-user1688** [BetterAndroid/android-notification-icon-project#366]
### APP 名称

网易云游戏

### APP 包名

com.netease.android.cloudgame

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

有活动的时候会发起通知

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
