### ISSUE TITLE
[Request] 123云盘

### ISSUE THREAD

**Issue by Mc-user1688** [BetterAndroid/android-notification-icon-project#369]
### APP 名称

123云盘

### APP 包名

com.mfcloudcalculate.networkdisk

### 下载渠道、来源地址链接

www.123pan.com

### 简单描述适配的通知图标使用场景

在打开APP时会有

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
