### ISSUE TITLE
[Request] 随身工作台

### ISSUE THREAD

**Issue by chilan666** [BetterAndroid/android-notification-icon-project#370]
### APP 名称

随身工作台

### APP 包名

com.oplus.work

### 下载渠道、来源地址链接

https://wwad.lanzouw.com/i0gr313549xg

### 简单描述适配的通知图标使用场景

打开OPPO设置里的随身工作台功能，会弹出通知，就是彩色的
![Screenshot_2023-07-26-11-02-10-67_df198e732186825c8df26e3c5a10d7cd](https://github.com/fankes/AndroidNotifyIconAdapt/assets/105541799/962bcf75-f893-42da-9266-53146e28f227)

### 确认一下你提交的信息

- [ ] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by fankes** [comment]
？
