### ISSUE TITLE
[Request] 古文岛适配

### ISSUE THREAD

**Issue by benderxve** [BetterAndroid/android-notification-icon-project#372]
### APP 名称

古文岛

### APP 包名

com.guwendao.gwd

### 通知图标颜色 (HEX)

#FFC5CFCE

### 下载渠道、来源地址链接

手机自带应用市场

### 简单描述适配的通知图标使用场景

每日诗句推送无原生图标

### 通知单色图标适配素材 (大小 50x50~72x72)

无

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
