### ISSUE TITLE
[Request] 库迪咖啡app通知图标适配

### ISSUE THREAD

**Issue by TENGERZ** [BetterAndroid/android-notification-icon-project#374]
### APP 名称

库迪咖啡

### APP 包名

com.cotticoffee.cotticlient

### 下载渠道、来源地址链接

OPPO软件商店

### 简单描述适配的通知图标使用场景

应用自带推送消息以及hms推送是彩色图标
![Screenshot_2023-08-04-01-22-18-08_b783bf344239542886fee7b48fa4b892](https://github.com/fankes/AndroidNotifyIconAdapt/assets/36339026/1671db9f-22b8-403b-a99b-198455e31366)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
