### ISSUE TITLE
[Request] 请求适配智行火车票12306抢票（另一个包名）

### ISSUE THREAD

**Issue by KIITTID** [BetterAndroid/android-notification-icon-project#375]
### APP 名称

智行火车票12306抢票

### APP 包名

com.yipiao

### 下载渠道、来源地址链接

https://www.coolapk.com/game/com.yipiao

### 简单描述适配的通知图标使用场景

自带推送通知。

### 通知单色图标适配素材 (大小 50x50~72x72)

![256](https://github.com/fankes/AndroidNotifyIconAdapt/assets/32213083/b302e890-cdc0-42bb-893b-3ead97f261e1)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by NekoMua** [comment]
@fankes 
com.yipiao 在APP适配文件的4354~4362行有适配
