### ISSUE TITLE
[Request] 螞蟻銀行(香港) 适配

### ISSUE THREAD

**Issue by leechakto** [BetterAndroid/android-notification-icon-project#378]
### APP 名称

螞蟻銀行(香港)

### APP 包名

com.alipay.antbank.hk.portal

### 下载渠道、来源地址链接

https://play.google.com/store/apps/details?id=com.alipay.antbank.hk.portal

### 简单描述适配的通知图标使用场景

该应用未适配，所有通知都是彩色图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
