### ISSUE TITLE
[Request] 适配'天星银行'

### ISSUE THREAD

**Issue by leechakto** [BetterAndroid/android-notification-icon-project#379]
### APP 名称

天星银行

### APP 包名

com.airstarbank.mobilebanking

### 下载渠道、来源地址链接

https://play.google.com/store/apps/details?id=com.airstarbank.mobilebanking

### 简单描述适配的通知图标使用场景

该应用未适配，所有通知都是彩色图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by fankes** [comment]
请描述使用场景和频率以便决定是否适配
