### ISSUE TITLE
[Request] 123云盘

### ISSUE THREAD

**Issue by Mc-user1688** [BetterAndroid/android-notification-icon-project#380]
### APP 名称

123云盘

### APP 包名

com.mfcloudcalculate.networkdisk

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

打开APP上传/下载软件后触发

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
