### ISSUE TITLE
[Request] 光·遇 光遇vivo渠道服适配

### ISSUE THREAD

**Issue by Memory2314** [BetterAndroid/android-notification-icon-project#385]
### APP 名称

光·遇

### APP 包名

com.netease.sky.vivo

### 下载渠道、来源地址链接

http://info.appstore.vivo.com.cn/detail/2902164

### 简单描述适配的通知图标使用场景

有心火收的时候触发，希望在已有图标添加vivo渠道服的适配

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
