### ISSUE TITLE
[Request] 乐橙

### ISSUE THREAD

**Issue by yufq10129** [BetterAndroid/android-notification-icon-project#386]
### APP 名称

乐橙

### APP 包名

com.mm.android.lc

### 下载渠道、来源地址链接

https://www.imou.com/wap/#/pages/service/download

### 简单描述适配的通知图标使用场景

状态栏通知

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
