### ISSUE TITLE
[Request] 招乎app图标适配

### ISSUE THREAD

**Issue by qiuham** [BetterAndroid/android-notification-icon-project#388]
### APP 名称

招乎

### APP 包名

com.cmbchina.amoffice

### 通知图标颜色 (HEX)

#e1001a

### 下载渠道、来源地址链接

cmbt.cn/cmboa

### 简单描述适配的通知图标使用场景

通讯工具，理论上类似微信，有小米推送

### 通知单色图标适配素材 (大小 50x50~72x72)

![招乎图标](https://github.com/fankes/AndroidNotifyIconAdapt/assets/140688878/7252baf4-0a47-4e2a-b59c-6524606ca8aa)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
这是不需要适配了？

**Comment by qiuham** [comment]
c7142d

> 这是不需要适配了？

图标是不是不符合要求，需要重新传么
