### ISSUE TITLE
[Request] 招乎图标适配

### ISSUE THREAD

**Issue by qiuham** [BetterAndroid/android-notification-icon-project#389]
### APP 名称

招乎

### APP 包名

com.cmbchina.amoffice

### 通知图标颜色 (HEX)

#e1001a

### 下载渠道、来源地址链接

cmbt.cn/cmboa

### 简单描述适配的通知图标使用场景

通讯工具，理论上类似微信，不确定有没有mipush

### 通知单色图标适配素材 (大小 50x50~72x72)

![招乎图标单色](https://github.com/fankes/AndroidNotifyIconAdapt/assets/140688878/5171cd99-47dd-4cbe-8031-b687777b6482)
抠了个图，不知道行不行

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
