### ISSUE TITLE
[Request] 申请适配Kim图标

### ISSUE THREAD

**Issue by deusyu** [BetterAndroid/android-notification-icon-project#396]
### APP 名称

Kim

### APP 包名

com.yiqixie.kem

### 下载渠道、来源地址链接

https://kim.kuaishou.com/

### 简单描述适配的通知图标使用场景

接入的小米推送，是我司的IM工具，目前外部可以下载使用。

### 通知单色图标适配素材 (大小 50x50~72x72)

![kim_icon](https://github.com/fankes/AndroidNotifyIconAdapt/assets/42929363/dfb89e45-21cf-4554-8f9c-31cb6237ba6c)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
