### ISSUE TITLE
[Request] TTS Server

### ISSUE THREAD

**Issue by troublewind** [BetterAndroid/android-notification-icon-project#397]
### APP 名称

TTS Server

### APP 包名

com.github.jing332.tts_server_android

### 通知图标颜色 (HEX)

#00DDB3

### 下载渠道、来源地址链接

https://github.com/jing332/tts-server-android/releases

### 简单描述适配的通知图标使用场景

TTS播放时有通知

### 通知单色图标适配素材 (大小 50x50~72x72)

![3a](https://github.com/fankes/AndroidNotifyIconAdapt/assets/107900115/41070e90-8b5f-454c-bb83-7ab3fd0ef4b8)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
