### ISSUE TITLE
[Request] 小鹅通

### ISSUE THREAD

**Issue by BillyLYC** [BetterAndroid/android-notification-icon-project#402]
### APP 名称

小鹅通

### APP 包名

com.xiaoe.client

### 下载渠道、来源地址链接

https://www.xiaoe-tech.com/?channel=1285-1360-1361-15322&from_click=xe_know_app_02

### 简单描述适配的通知图标使用场景

小米推送，播放中，显示为彩色

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
