### ISSUE TITLE
[Request] 用药助手

### ISSUE THREAD

**Issue by BillyLYC** [BetterAndroid/android-notification-icon-project#403]
### APP 名称

用药助手

### APP 包名

cn.dxy.medicinehelper

### 下载渠道、来源地址链接

https://drugs.dxy.cn/

### 简单描述适配的通知图标使用场景

小米推送通知的时候

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
