### ISSUE TITLE
[Request] jagat果汁

### ISSUE THREAD

**Issue by HanBiWolf** [BetterAndroid/android-notification-icon-project#408]
### APP 名称

Jagat果汁

### APP 包名

cn.jagat.main

### 下载渠道、来源地址链接

jagat.cn

### 简单描述适配的通知图标使用场景

日常常驻后台信息

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
