### ISSUE TITLE
[Request] Steam Chat

### ISSUE THREAD

**Issue by xiangfa-test** [BetterAndroid/android-notification-icon-project#409]
### APP 名称

Steam Chat

### APP 包名

com.valvesoftware.android.steam.friendsui

### 下载渠道、来源地址链接

Play商店

### 简单描述适配的通知图标使用场景

应用fcm推送及应用自身推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
