### ISSUE TITLE
[Request] 墨迹天气

### ISSUE THREAD

**Issue by ybhgl** [BetterAndroid/android-notification-icon-project#413]
### APP 名称

墨迹天气

### APP 包名

com.moji.mjweather

### 下载渠道、来源地址链接

https://www.coolapk.com/apk/com.moji.mjweather

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
