### ISSUE TITLE
[Request] 适配app图标中关村在线

### ISSUE THREAD

**Issue by aKuan111** [BetterAndroid/android-notification-icon-project#414]
### APP 名称

中关村在线

### APP 包名

com.zol.android

### 下载渠道、来源地址链接

https://m.zol.com.cn/

### 简单描述适配的通知图标使用场景

小米推送

### 通知单色图标适配素材 (大小 50x50~72x72)

![256](https://github.com/fankes/AndroidNotifyIconAdapt/assets/118877878/9e7096b8-aea3-40c3-94fb-0b06c32feff9)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
