### ISSUE TITLE
请求适配edge浏览器[Request]

### ISSUE THREAD

**Issue by xswl-yyds** [BetterAndroid/android-notification-icon-project#416]
### APP 名称

edge

### APP 包名

com.microsoft.emmx

### 下载渠道、来源地址链接

https://play.google.com/store/apps/details?id=com.microsoft.emmx

### 简单描述适配的通知图标使用场景

在其他客户端使用“发送标签页到你的设备”时候选择手机时，手机上会收到通知

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
