### ISSUE TITLE
彩云天气pro[Request]

### ISSUE THREAD

**Issue by xswl-yyds** [BetterAndroid/android-notification-icon-project#417]
### APP 名称

彩云天气pro

### APP 包名

com.nowcasting.huawei

### 下载渠道、来源地址链接

啊啊啊

### 简单描述适配的通知图标使用场景

PS: 这个图标和彩云天气图标是一样的

彩云天气已经适配了，这个是彩云天气pro，这软件之前是在华为应用市场里面购买的，但是不知道为什么下架找不到下载链接了，没办法只能网盘分享了，抱歉。虽然下架了但是还能下载使用，且其他手机也可以(需要配合华为应用市场)，与已适配的彩云天气包名的后面不一样

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
