### ISSUE TITLE
部分APP icon在HyperOS失效

### ISSUE THREAD

**Issue by SaKongA** [BetterAndroid/android-notification-icon-project#421]
机型: 小米13Pro
系统版本：1.0.23.11.8DEV
部分APP通知图标失效如：

哔哩哔哩
抖音
QQ音乐 For MIUI
应用商店

等等

望修复，谢谢！

**Comment by fankes** [comment]
无法修复，因为截图也没有详细说明也没有，如果是模块的 bug，请反馈到 [MIUINativeNotifyIcon](https://github.com/fankes/MIUINativeNotifyIcon) 这里不受理，谢谢。
