### ISSUE TITLE
[Request] 请求适配：GKD

### ISSUE THREAD

**Issue by li0625** [BetterAndroid/android-notification-icon-project#427]
### APP 名称

GKD

### APP 包名

li.songe.gkd

### 下载渠道、来源地址链接

https://github.com/gkd-kit/gkd

### 简单描述适配的通知图标使用场景

红米note12t 在状态栏 显示彩色 通知栏图标是默认的
使用这个软件默认常驻通知栏 就会触发

### 通知单色图标适配素材 (大小 50x50~72x72)

![GKD](https://github.com/fankes/AndroidNotifyIconAdapt/assets/104386128/25ccd536-299b-43de-990d-c23e59e968be)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua

**Comment by fankes** [comment]
可以联系到开发者的请联系软件开发者适配，比如去提一个 issue，通知规范是每个开发者都应该遵守的，而不是我们强制去适配
