### ISSUE TITLE
[Request] edge

### ISSUE THREAD

**Issue by TENGERZ** [BetterAndroid/android-notification-icon-project#433]
### APP 名称

edge

### APP 包名

com.microsoft.emmx

### 下载渠道、来源地址链接

google play

### 简单描述适配的通知图标使用场景

![Screenshot_2023-11-25-17-46-23-957_com miui home](https://github.com/fankes/AndroidNotifyIconAdapt/assets/36339026/00f93d17-5cbd-48a1-8df1-68be3f5bfe27)
小米状态栏显示彩色图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
