### ISSUE TITLE
[Request] 请求适配：GKD

### ISSUE THREAD

**Issue by RangeZero** [BetterAndroid/android-notification-icon-project#435]
### APP 名称

GKD

### APP 包名

li.songe.gkd

### 下载渠道、来源地址链接

https://github.com/gkd-kit/gkd

### 简单描述适配的通知图标使用场景

通知栏常驻彩色图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
Same as #427
