### ISSUE TITLE
[Request] 适配简讯

### ISSUE THREAD

**Issue by KIITTID** [BetterAndroid/android-notification-icon-project#442]
### APP 名称

简讯

### APP 包名

com.tipsoon.android

### 通知图标颜色 (HEX)

#000000

### 下载渠道、来源地址链接

http://app.xiaomi.com/detail/468209

### 简单描述适配的通知图标使用场景

在任何时候下都是黑色的图标.

### 通知单色图标适配素材 (大小 50x50~72x72)

![简讯](https://github.com/fankes/AndroidNotifyIconAdapt/assets/32213083/a1fb3868-004e-45e6-a85e-3a9d913412a7)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
z

**Comment by fankes** [comment]
@NekoMua
