### ISSUE TITLE
[Request] 雷速体育

### ISSUE THREAD

**Issue by kotuyako** [BetterAndroid/android-notification-icon-project#443]
### APP 名称

雷速体育

### APP 包名

com.leisu.sports

### 通知图标颜色 (HEX)

#FFD82D44

### 下载渠道、来源地址链接

https://m.leisu.com/app

### 简单描述适配的通知图标使用场景

![Screenshot_2023-12-18-01-20-52-194_com miui home-edit](https://github.com/fankes/AndroidNotifyIconAdapt/assets/113581677/df81572d-624c-4f0c-bfd1-3720be579558)

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
