### ISSUE TITLE
[Request] 木马课堂

### ISSUE THREAD

**Issue by XiaMuqingyuan** [BetterAndroid/android-notification-icon-project#444]
### APP 名称

木马课堂

### APP 包名

com.mmkt.online.edu

### 下载渠道、来源地址链接

小米商店

### 简单描述适配的通知图标使用场景

老师发起签到会在状态栏出现图标

### 通知单色图标适配素材 (大小 50x50~72x72)

![Uploading app_icon.png…]()

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by XiaMuqingyuan** [comment]
test

**Comment by fankes** [comment]
[Uploading app_icon.png…](https://github.com/fankes/AndroidNotifyIconAdapt/issues/444) 请上传成功后再提交

**Comment by XiaMuqingyuan** [comment]
![app_icon](https://github.com/fankes/AndroidNotifyIconAdapt/assets/99756780/bf1c2f4e-175d-4d6b-bb00-441a0cb1cd2f)

**Comment by fankes** [comment]
@NekoMua
