### ISSUE TITLE
[Request] 适配飞常准

### ISSUE THREAD

**Issue by KIITTID** [BetterAndroid/android-notification-icon-project#447]
### APP 名称

飞常准

### APP 包名

vz.com

### 下载渠道、来源地址链接

 http://app.xiaomi.com/detail/2023

### 简单描述适配的通知图标使用场景

重要的航班查询软件

### 通知单色图标适配素材 (大小 50x50~72x72)

![飞](https://github.com/fankes/AndroidNotifyIconAdapt/assets/32213083/75506326-e31e-4676-87dd-ea64f77a127b)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
