### ISSUE TITLE
[Request] 金山协作

### ISSUE THREAD

**Issue by Cai1415** [BetterAndroid/android-notification-icon-project#452]
### APP 名称

金山协作

### APP 包名

com.kingsoft.xiezuo

### 下载渠道、来源地址链接

https://kimxz.com/mobileDownload

### 简单描述适配的通知图标使用场景

原生 Android14，pixel 7 pro，hms 推送， 通知未适配显示白块
![Uploading Screenshot_20240116-111749.png…]()

### 通知单色图标适配素材 (大小 50x50~72x72)

(大小 50x50~72x72)

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
