### ISSUE TITLE
[Request] [通知图标优化惯性反馈] GKD

### ISSUE THREAD

**Issue by ENDDREAM-ZM** [BetterAndroid/android-notification-icon-project#454]
### APP 名称

GKD

### APP 包名

li.songe.gkd

### 下载渠道、来源地址链接

https://github.com/gkd-kit/gkd

### 简单描述适配的通知图标使用场景

显示在状态栏和通知栏就是彩色的
打开软件可触发推送通知 可使用无障碍触发推送通知

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
#427 #435
