### ISSUE TITLE
[Request] 企查查-企业查询 请求适配企查查

### ISSUE THREAD

**Issue by 1889737514** [BetterAndroid/android-notification-icon-project#455]
### APP 名称

企查查-企业查询

### APP 包名

com.android.icredit

### 通知图标颜色 (HEX)

#FF259AF7

### 下载渠道、来源地址链接

各大应用商店

### 简单描述适配的通知图标使用场景

小米推送

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
