### ISSUE TITLE
[Request] InstallerX请求适配

### ISSUE THREAD

**Issue by ghost** [BetterAndroid/android-notification-icon-project#458]
### APP 名称

InstallerX

### APP 包名

com.rosan.installer.x

### 下载渠道、来源地址链接

https://t.me/InstallerX

### 简单描述适配的通知图标使用场景

在安装应用时，会有通知弹窗，希望可以优化通知图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
#454
