### ISSUE TITLE
[Request] 拼多多商家版

### ISSUE THREAD

**Issue by lsyysa** [BetterAndroid/android-notification-icon-project#463]
### APP 名称

拼多多商家版

### APP 包名

com.xunmeng.merchant

### 下载渠道、来源地址链接

各大商店或者酷安

### 简单描述适配的通知图标使用场景

没有适配  来消息状态栏就是原来图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
