### ISSUE TITLE
[Request] 请求适配：UU跑腿跑男端

### ISSUE THREAD

**Issue by Neverland0316** [BetterAndroid/android-notification-icon-project#465]
### APP 名称

UU跑腿跑男端

### APP 包名

com.slkj.paotui.worker

### 下载渠道、来源地址链接

华为应用市场

### 简单描述适配的通知图标使用场景

OPPO状态栏

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
