### ISSUE TITLE
[Request] 百度网盘联运版适配

### ISSUE THREAD

**Issue by hjjhgyh** [BetterAndroid/android-notification-icon-project#468]
### APP 名称

百度网盘联运版

### APP 包名

com.baidu.netdisk.xiaomi.appunion

### 下载渠道、来源地址链接

https://www.123pan.com/s/YeY8Vv-0kPoA.html  提取码76ks

### 简单描述适配的通知图标使用场景

使用百度网盘下载时会弹出图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
