### ISSUE TITLE
[Request] 京东小家图标适配

### ISSUE THREAD

**Issue by l767305605** [BetterAndroid/android-notification-icon-project#471]
### APP 名称

京东小家

### APP 包名

com.jd.iots

### 下载渠道、来源地址链接

https://smart.jd.com/app?ivk_sa=1024320u

### 简单描述适配的通知图标使用场景

定时启动电器推送通知

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
