### ISSUE TITLE
[Request] 彩云天气Pro

### ISSUE THREAD

**Issue by Makabaklzq** [BetterAndroid/android-notification-icon-project#474]
### APP 名称

彩云天气Pro

### APP 包名

com.nowcasting.huawei

### 下载渠道、来源地址链接

华为应用商店

### 简单描述适配的通知图标使用场景

HMS推动为彩色图标

### 通知单色图标适配素材 (大小 50x50~72x72)

套彩云天气图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
