### ISSUE TITLE
[Request] 请求适配深蓝汽车通知图标

### ISSUE THREAD

**Issue by Jerryfu21** [BetterAndroid/android-notification-icon-project#485]
### APP 名称

深蓝汽车

### APP 包名

deepal.com.cn.app

### 下载渠道、来源地址链接

小米应用商店

### 简单描述适配的通知图标使用场景

完全没有适配的app，只有有软件通知消息就默认在通知栏出现原icon

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
