### ISSUE TITLE
[Request] 请求适配森空岛状态栏图标

### ISSUE THREAD

**Issue by KanzakiZukasa** [BetterAndroid/android-notification-icon-project#486]
### APP 名称

森空岛

### APP 包名

com.hypergryph.skland

### 下载渠道、来源地址链接

https://www.skland.com

### 简单描述适配的通知图标使用场景

ColorOS14没有对森空岛做图标适配，在开启通知时只会显示一个icon

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
