### ISSUE TITLE
[Request] 拼多多商家版请求适配

### ISSUE THREAD

**Issue by Youngfella1** [BetterAndroid/android-notification-icon-project#491]
### APP 名称

拼多多商家版

### APP 包名

com.xunmeng.merchant

### 下载渠道、来源地址链接

https://mobile.baidu.com/item?pid=3209183&source=aladdin%40wise_app13%40title&ala=strong%405001258356%403209183%40wandoujia%40title%40%E6%8B%BC%E5%A4%9A%E5%A4%9A%E5%95%86%E5%AE%B6%E7%89%88&ala=app_mobile_simple%405267%40s%40%E6%8B%BC%E5%A4%9A%E5%A4%9A%E5%95%86%E5%AE%B6%E7%89%88%4011241163217275646827%40title&docid=5001258356&alaSid=&from=1022306o&sid=

### 简单描述适配的通知图标使用场景

小米推送

### 通知单色图标适配素材 (大小 50x50~72x72)

![Uploading IMG_20240710_014233.jpg…]()

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
