### ISSUE TITLE
[Request] 请求适配：金十数据

### ISSUE THREAD

**Issue by edge660335** [BetterAndroid/android-notification-icon-project#494]
### APP 名称

金十数据

### APP 包名

com.jin10

### 通知图标颜色 (HEX)

#469be0

### 下载渠道、来源地址链接

https://62443efba9b1f0278a720f6a2bcf96b0.rdt.tfogc.com:49156/imtt.dd.qq.com/sjy.20002/sjy.00004/16891/apk/0B0B7601C2E27B608BB63A646124DA08.apk?mkey=66a6f93d229aecdf833eb5fe8c189e8e&arrive_key=9336611880&fsname=com.jin10_6.15.0.apk&hsr=10947540&cip=182.204.53.66&proto=https

### 简单描述适配的通知图标使用场景

在类原生系统中是白方块，HMS推送目前没有适配，目前也还是白色方块

### 通知单色图标适配素材 (大小 50x50~72x72)

![xhuVpEi__400x400](https://github.com/user-attachments/assets/77fa9a78-e3b2-4c65-9ae5-2347462fc170)

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
