### ISSUE TITLE
[Request] x 前几天合并文件有错误

### ISSUE THREAD

**Issue by InkJiang** [BetterAndroid/android-notification-icon-project#496]
### APP 名称

x

### APP 包名

x

### 下载渠道、来源地址链接

x

### 简单描述适配的通知图标使用场景

作者你好，前几天合并的图标文件位置有错误，麻烦手动调整一下。

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by InkJiang** [comment]
![Uploading Screenshot_2024-08-09-12-18-11-731_com.mmbox.xbrowser-edit.jpg…]()

**Comment by fankes** [comment]
你重新 fork 调整完后 pr 给我
