### ISSUE TITLE
[Request] 拍机堂

### ISSUE THREAD

**Issue by 16rab** [BetterAndroid/android-notification-icon-project#499]
### APP 名称

拍机堂

### APP 包名

com.aihuishou.opt

### 下载渠道、来源地址链接

https://www.paijitang.com/

### 简单描述适配的通知图标使用场景

默认彩色，没有适配

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
