### ISSUE TITLE
[Request] 雷神加速器

### ISSUE THREAD

**Issue by JackA1ltman** [BetterAndroid/android-notification-icon-project#500]
### APP 名称

雷神加速器

### APP 包名

com.nn.accelerator.box

### 下载渠道、来源地址链接

https://www.leigod.com/m/

### 简单描述适配的通知图标使用场景

ColorOS(OPPO Push)系统下，优惠等信息推送会变成彩色图标

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
