### ISSUE TITLE
[Request] 适配 Scene 图标

### ISSUE THREAD

**Issue by TomyJan** [BetterAndroid/android-notification-icon-project#509]
### APP 名称

Scene

### APP 包名

com.omarea.vtools

### 通知图标颜色 (HEX)

(常驻通知颜色会随调度策略改变)

### 下载渠道、来源地址链接

http://vtools.omarea.com/

### 简单描述适配的通知图标使用场景

图标一直是应用自身图标，暂时没发现出现其他图标

### 通知单色图标适配素材 (大小 50x50~72x72)

我没有...这个也必须提供吗

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by TomyJan** [comment]
哦抱歉更正下，刚升级完系统没反应过来此应用是有单色图标的，但是有时候 (在我目前的 HyperOS Beta 上是大多时候) 会变成白色方块，烦请开发者分析下

**Comment by fankes** [comment]
https://github.com/fankes/MIUINativeNotifyIcon/issues/202

试一下 CI 版本，如果还有问题重新解锁即可刷新图标
