### ISSUE TITLE
[Request] 适配适配，GKD居然没人用么

### ISSUE THREAD

**Issue by 9674454** [BetterAndroid/android-notification-icon-project#517]
### APP 名称

GKD

### APP 包名

li.songe.gkd

### 下载渠道、来源地址链接

https://pan.quark.cn/s/f01561504495#/list/share

### 简单描述适配的通知图标使用场景

全场景都是彩色的

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
#427，提问前建议先搜一下历史
