### ISSUE TITLE
[Request] 网商银行

### ISSUE THREAD

**Issue by ZhiBai6** [BetterAndroid/android-notification-icon-project#519]
### APP 名称

网商银行

### APP 包名

com.mybank.android.phone

### 下载渠道、来源地址链接

https://app.mi.com/details?id=com.mybank.android.phone&ref=search

### 简单描述适配的通知图标使用场景

通知时都是彩色,没有对应的适配规则

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
@NekoMua
