### ISSUE TITLE
MIUI-录音助手

### ISSUE THREAD

**Issue by moonbai** [BetterAndroid/android-notification-icon-project#78]
{
  "appName": "录音助手", // APP 名称
  "packageName": "com.miui.audiomonitor", // APP 包名
  "isEnabled": true, // 是否默认启用替换彩色图标 - 关闭后将全部停止替换
  "isEnabledAll": false, // 是否默认启用替换全部图标
  "iconBitmap": "iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAjqSURBVGiBzVp7UJTXFf+d+33Lwu4SHlVjWi07TkpbUaOO1hofbCcaRYMoyhqiFtBEq2nqmKl2orauVpOmnck0nakTHxE0Krr4SrAaq0kWnTQ6iS8QNI6xS7AzvgWBLbD73dM/9lFgeOx+bGJ+f+137znnnt93zn2c+y0hCnA6nTGKbB4khBhChFGSMZCIUsDcC0RmAABzIxPdAnM1CVFJzBeZudwLwwW73d7SUx9IryIzi/f37fw5Q0xmIItA/QFYAKhh2vUx0EjAdWIc0aR2IKXOUzFi0SKvHn8iJlJYWBibYDYOI8ISBqYQkKTHTjswgW4x8+cgeluNtXyWmZnpicRA2A4wMx3cu/cnJLQVIJoGIDlid8MbqR4knF7p+0tOztyrRMThaCnhmh+alrqAFGwFKB1AnG4/uwUZAQwXRNO/rKyo21ty4HxYWt0JOJ3OZJW8Gwi0KFydKMEfCaJ34qSyerLdfr8r4S6dKi7e1j9Wif0bCJmIIHrRBDNLIpSST7wyPTe3pjO5TokUF2/rH6saNwH0LB4RiVbQmHFcaLSwMzIdEnE6nckqvNuI6Dk8ehJBaAAfZo9vQXZe3r32naIjDQO864FHl06dQAHoOWFW13fU2SYizEyHSnbPB9GW9n1RAUfFKksNC7Nn577bemlu88bT0p78sSLEuwAei8qQbYZnMAjUc6sEwcOvVpZ/uKfkwJ1gYyi1SktLTQaI5WD0RxRICCFgNpmQmJiAxMQEmMxmiA4TOXIQqJ8ksaKwsDA22KYGf/iaGkaDYI/KSMzuHbuKXXNz7e5/7D8Gj8eDlxcvQkJCvPX+vVpbc0uzNSAHvSEiIDPJErsZwL8Cz8AXmzYZapLi9wf2i54QgMlicp89V+5YuXrN9o5Eyk4czWv2NjsaGzzWEBGdhBi8a8asF35JRFIAQHWCaTARRuon4CcBJrfZbOqUBACkT8jYvnbtnxxNzc1uv25PokIZB5y7RgOBOaIIJZuBx3VZ81sEiNC7T7JrbPqkTkkE8enp09vr6+tdfr1AI4d1NmyPJCGUSQAgnE5nDBNPQRQmePXXNe5wZasuX3EzE5gDw+qLCjE4y+l0xggDvEOZaYAeK+2hxsSELXvz5u3Qb33B8IPAP1Rk8yCViIYAMOs35YcQouNjQhfyrZyB/oQgsxBiiGCip9BqGf628OQAaytfepTVKhFGCZYyradOBVFV+WXYsqNGjQrEoAd55QdJxkABQkpPLQXR2BR+mX38o4/AUTp8ESFFEOtbdoUQMBqNbXL9ZyNGWLtQaYOMSZNAgkAhWzFtbEUERi8RuneKACTIXXbyVNGRD485lrzyapGiKm4GYIqLs+XkzEgPx0aMUbESAMWgwHXyU/e6DW8WSdaKSFDYS/j/HSKzrklujDG433r77w4A1QAQbzYX1tY9zPd6vVZFUWwAyrrSt1gs6SDFxgzEGo0o3L7dVVv7sGDGrDkpJcXvFamqEnZkgxBgboyYCZO1YF5uaLD7Dx64AaB37+8ha2pGt+rPz8q2/dfjsTIzVEV1A6Io0FVtsejYCZgbBQh3I9WTLK0JSUm24PP1626AGbdu30FLS/e3n6bHLJA+CQJBKKqrtrY2FMFr176K1B2A6JZg9qdHJPD5NFRVXQk9HznyTxcpwg0AcbFx3abF7Vt3rF5vC0BAfX1daE4sXvxSenJycsRpxczVQhCqIlWUUmLpr5eEBvzk1Kmy2gd1LgAwmy22Zb95Oa8z3aOHD+TZs6fbGASDqriXLf+dK9hnNhptJlP3L6I9SKBSZcYZEBYAMESkzdI2bNjg9PPnK8oAYLXDUbRl40ZbU3OTdfz4sY70X4yzKSD379f8EcOHD7NmTs2wWizxaHj40AoiKzG7IRTHtWvuUFqNHTfGyjLiDdJHTBdVKWW5UEQjQImRaLf4fNYZ0zLzg0Ru3LhZdvb8WcfIkSMcngaPVUrKhwAcf1gFKAT2amhoqAcEgZjd/66pdrz625WhI39qamoea2zTsT82MnO5Msuee08QzyYd9cgTT/RNrKy6dOH27bvVAPCx69RFrUVeGDNmFHyalshAIksZuD0hEBE0nw/Llq885Nx3cG3QjsUSm/7Wm2/8VTWoEacVgMteGNYTABws2bUOoNXQcV6oe/iwKH/Brwrat7/22vL0ugd1tqkZE9HQ4MHNmzfRp08vvLR4KVRVLaqtrQ0tMvv27CxUFJGvgwQz+I3snDmrCAAOlRQ/zeBS6PlUwHDX/OeGa92G14vu3q3tciPsCK+vX5v309QfOUCIPBqMW1LRpsycOe+cCgAtrJwxkO8IgLkRGyNY+/frl79l40Zb5ZXLrr0lh4oqKiq6JVRQMC/9mfHj8s1mi00XCQAM/lyr+OqS340ASorfe1pVFX1RaQWhCHfFxQrXiU/K3BfKy/H9vn0xefKz8Hg8+Nh1EsOHDkHWtExrbIxRN4EA6kly9vTZc04ArQqqhibfucR48QGY9ORqCFKT1rRBaflpg/xlDgWKJmbGpIkTemK6DRgoqW/WPgs+t5nch5w7B0qiYwT6Qfu+7xIYfENhOSHLPi9UybUpALJy5lwmhuPbdy0ysEZrp+XMvdq6rcO3fqBk9zsEvIjv1mcFMLMEYXN2zpzF7fs6Lsk83lVgPgxA+6adiwAaEUrh8a3uqLPTeXCoeFt/qcRsJhIT8egjozHL40JTOv301mmRPD13fo3QWhYCfJiZ5TfnY7fQGHy4KxJAF0QAPxkvG+YLwmZE4d4mUgTu6bfC41vQFYmAbHjYv2f3i6TwGgL167mLXYP8284NKbFu5vMvbA1TJzwwM31QsjNVI2UFATkA4nV72jXuM2SpYPw5K2fO5XD/whHxprdjxw6z2aiMJsJSAo0EoY8eO+3AAB4w+KiA2PigoelcQUFBUyQGdDvwxaZNhuoE02BSxEwCZTAwgPyX4V1eMVFgrjHgA7iRga8JeF9KPqZRzGm73a5ryY/KMcTpdMYY4B1KREOY6CmWMg2EFGI83uoCsAGEu2BUE/gyM85IKcs1YbwUjT+e/Q8NZXAdtWOV8QAAAABJRU5ErkJggg==", // 位图数据 Base64 字符串
  "iconColor": "#FFFF3A3A", // 通知栏中显示的图标颜色 - 不设置使用系统默认颜色 (不设置颜色可删除此项)
  "contributorName": "Mars" // 贡献者昵称
}

**Comment by moonbai** [comment]
手机端无法操作，请大佬帮忙push一下～

**Comment by fankes** [comment]
加上了
