### ISSUE TITLE
联通流量监控

### ISSUE THREAD

**Issue by bk227918** [BetterAndroid/android-notification-icon-project#79]
增加图标
![ic_launcher_foreground](https://user-images.githubusercontent.com/63150136/161582225-23eceaac-260a-4e62-baa1-2e33971b0de8.png)
应用包名:com.benten.jiankong
应用名称:联通流量监控

**Comment by fankes** [comment]
请提供单色图标

**Comment by bk227918** [comment]
![c7b5c1fdd2e330c5](https://user-images.githubusercontent.com/63150136/161594992-76e11048-ee75-4714-bea7-60d929747457.jpg)
