### ISSUE TITLE
图标适配-摸鱼kik

### ISSUE THREAD

**Issue by moonbai** [BetterAndroid/android-notification-icon-project#82]
{
  "appName": "摸鱼kik", // APP 名称
  "packageName": "com.sohu.supermarie", // APP 包名
  "isEnabled": true, // 是否默认启用替换彩色图标 - 关闭后将全部停止替换
  "isEnabledAll": false, // 是否默认启用替换全部图标
  "iconBitmap": "iVBORw0KGgoAAAANSUhEUgAAAC8AAAAyCAYAAADMb4LpAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAvVSURBVGiBzZp/dJTllcc/93lnJpMEFEhSYaLisTUV0S3+4hSVSrV1jy7WtQVbtV11V6PVUmuLhNkQ5uYHoJQWlSrKsnZR1KPBUj0tR+naCmU5ZVvU7ZHlaO3u2iMpEqhGIEwy8z53/3gnOIQJTFy79XvOnEnue5/n+b73uc997n2eEYYBVW0TkTCTybSqakJEbjezT2az2TuTyWQIHA88CnwH2KiqHqCxsTGeSqUe995vcs79cHC/vb29tnjx4r3D4QIgZZKOmVlKRFYBNWY2XUQeB84B4sAewAMVwChgL/B9VVWA+fPnX+qcexbIAe+VGCKXz+cv6ejo2D4c8rFylLz3Nzjn7gMSgIjIE9779c65DZQ2gAEvDfzjnDPguyX0TgauAnbEYrG3h0N8OOQ3OeduI3KHkcBtQRB83MwWEb3QYPSHYbgOQFVTwM3AmSX0KgvfAfBpYN1wyLtylDo6Orar6sPA68BbqvqKmX0d2A38aNBnLVDlnJsKYGa3AZ8Dni+h+xhwL9ADPHT33XePHA75siw/BAIReSyTydyvqmOAOZSYBRGZCvxSVW8ekKnqbGClqr4L0Nra+oqZrcjlcmOI1ktZKMvyhQFTRIuxVPtjgDrgWGC0mSUH6YUA6XS6TlUfNLN5Zvakqn4GIAxDXy6PYpRl+ZaWlnOBnwNVwJYBuZmlM5nM18zsoK6IOCBpZodZsLq6OpHP598WkV7gv4DsByE9LPJmtg+4nWjBDuAXwB4RiQOfN7NeEdkIeBH5xXvvvffw4H7mzZu3A8ioatjX13f/okWL9gA458oK2YMxrEaquhY4jmgB/hPwMSIDTAEOAFuJwiTABlXtUNWNwDgRecCKp6gA770452aY2Sf7+vpOueuuu94pl88HWbBhT0+PjRo1apOZjQfuAPJmForIxcAG4MfAbwv6+8yszswypToTEYAeEfn2cIiXTb6xsTE+duzYq4AG4JmlS5ceUNUXgIVEUacjn8+vicViPwBOA3q7urp+OXPmzABYUdjMjoSsmWVnz55dvWTJkv0fKvlUKnUpsBLY7Zx7UlXPAdYTWexqM3u6o6PDq+oVwDzg3lQq5VKp1B+AR82snHFsxIgRtwCPlEu+LJ+fPXt29ahRo8bk8/n9qvonVR0jIheb2fOqekiuoqrOOTfFe/8msDsWi9WVS2bPnj27ly5deuBDJf//jXQ6XZdMJi8JwzDlnDvPzLaIyE7gOVXdOaD3kSKvqlXe+5udc1O99087536dz+cNIB6PTzKzLwGvVlZW3tvU1LT3I0NeVR2w3Hu/efv27as7OzvDIXS+AHylsrLypg+U28yaNauipqbmS8BMM6sXkc1hGK5qb29/eQhitSJyrZldCcTMbJ2I/Iuqdg3omNl5IrK9ra1tlape39nZuaq1tfUyM8sBu3p7e3/vvb+mra3todbW1tHZbPbvys5tilFTUzMPWA38rYicC9weBMFGVT2tBHEHPG1m9wAXAueLyALgeVWtKlL9fD6ff6bw9xdVVc1suvd+AjCrurr6751zDQB9fX3rzOysYZNvamo6FriUw9fLCKId9xA4584mytUPgZmNAw4mcCJSHYvFpPDsEyLyrpn9d+Hx5dlsdrX3fj1AIpEYD8SGRV5VR1VWVq4BTjSzxWEYTgbOBe4C3gUyc+fOHV2kf7r3/ikz+z1wQxAEDcBfA6tEZKSZtRQ2MoBfee+vjd5DXjOzySJS7Zw7AGxOJpO3BkFwzIIFC8YB94vI5uH4vJjZMhGZGIbh5e3t7VsKBMcC9UAeuDCZTP5IVR8lyu3vBHaKyBWququgXweMKVj7mxMmTPhX4KfAsyJysap+Hbiuq6vrQCqVMqK0+2Ezc0EQ1OdyubXAm3v37l1dtuWbm5uPBy4XkeYB4gVMA641s51Eydo04J+B5cDYMAxvHCBewFeB6cAzwL8552YVXqpfRO4AUsCcVCoVBy7y3qe9983AE2EYrgde3Ldv33VLlizZXzb5eDw+QUSSuVxuY7G8q6vraeBqEbnWOfeDQc22BkHwWrGgr68vA1wPfENEOoHJ6XS6rvACWeAN4Eqi2bjNOXeqc64beCyRSHxaVecO5D9lu433PnDO9Qyu8lesWJEDngJoaWmZGARB8eMeVT0kXi9atKibQv4yf/5875yLVVRUFDfaSVQ7vKKqu4/EqSzyc+fOHe2cuwmo895fSGSVwzuLxSYNStkvUNVxxfG8COKcm0x0gnDZzJkzV3V2doaq+lw5nKCMGraQZ/yYaCpFRDKqOmKwnqp+zMxmDRKPAm4p1a+qTgG+SGTA5RMnTryvsbExXi5xOEpu09bWdrb3/nHglCJdD7zgnGvu7u7+LUBtbe0F3vtFInJOiT6zwMogCO7ZtWvXWzU1NXFgBlEtMK5IzwMr9uzZ861ly5b1/Z/Ip9PpuoqKip8Ak4dQCYEBdxjH0V3wANBNFEKPG2JsD6zs6ur6RmEtHRFBKWE6na6pqKhYA5w3xCAQudyxhU85USte0B1xhD4FOHPkyJG1DQ0NP9u6desRj0QOG1RVXUVFxTLgM0cY5M8JB9xSX19/azmKh8B7fyXwZf6yub7z3i9Q1cNyomIcQrC5ubk+Ho9vAk76s1IrHy8BU1S1v9TDQywfj8fv5KNDHGAS0DjUw4OWb25uHh+Px1/h8PPIvzR29PX1nVnYmQ/BwfAWj8fv4MjEc8Cz3vv/CIKg38xmAGcxjMPaArLAGhF5HfBm9jdE+f5QayyVTCavp8TlRAAwZ86ckfF4fBlRKBsKbwObROSrRHG6Dfg4cMIwiIciMqfwAjcSbX7fNbPxIlI/RBsB6hoaGh4eHDpjANXV1V8ws6ORSPH+Qet4YAXRAdMUyo9Mb4Vh+IZzbi1R3D+eKH0+7AxzED6VSqXOBTYXCx1RkTFjGAQGMBb4T6Kj6nLxBpFrFucwVSJSfZR2AswcLHRNTU3HUKLGLAMvALUiMqtA6kjwBZ0lIvKmmZVzHtlbqGEHUurzikpGAGLJZPIMosL5deAhIj+8jMiXS86Gma3x3t8XBMFjZvYOkA7D8M0gCEpOfxiGQRAEJwDLReRXIvJlM+sgCoWl8Jt8Pn+Nc+4kEWk0s7NF5NRJkybVdnZ2HqwnYs65CWbWD/wReFVVly5cuHBMf39/K1GMPSxNFZGzgiBYR5SnnAA8EQTBnxjCd51zMaK6VYCTzOyioXSBl4ErEonEOO99q3PuO957BU7M5XITiQJHRN7MJgD7RGSRma1W1af6+/sfAb5VqOK/TeTfvwPWm9n1InLyoAFjlDj2KHrZwaJSukZ0GX2j936qc64LeM57v7XwPBCR0cUNYsCJRL6bDcOw1TnXIyJ13vvZwG+A83O5XBCPx/8IJERkJlAzFNFh4mXeX/D/AzzlvZ8Si8Ve8t7XiMiWQmV2XKnGDjgDwHt/k3NuOZAMwzAhIvcQ5esXJRKJvyKy1nSiY44PC/8OfAVYKSI9IlKTzWYf8d7nRORTZvYz4ALg1FKNiwuIGd77Dc65HzrnxorIDWZWISKVBw4c+Gk8Hj/NOfeAiAyseE90+buNqMjYVJCVGmMa0U3i6cDoonFvJIpC389kMs+p6unV1dXTzOzYHTt2LK6trT0ukUjcS/SbhiOSr3DO3Q9Mc84t9N4/mc1mraqq6hOVlZXXFK7qq4HXiNKEDc65X6tqN0ffZJbAwSLnDBE538wuAM4HFgBjMpnMg2EYjs7n85srKir219fXX2Vm/0h0TVQSg0u3OHC1934G0JNMJt/x3p9IZOG1zrkHu7u7X6qpqcm1tbV5ouhxNOIHUbi6fBF4UVWdmR3vnLvOzL4G3BoEwRvOOU90EX0yR8mbYkTT3lAkE6I6s44o97kbeKD41EtVPzdnzpwtVVVV/6Cq95RLfgDt7e2ntLS0/A74A9Cuqt9zzk01s6bCdX+pejgs7Cnvk/feL3POTefweP4TIK2qr5bo6JiqqqoHvfevD4e0ql6ybdu2F8IwnAV8s0jeCzzf2Nj481Qq9Vnge0Troxj74/H4tmLB/wJE+LodN533mQAAAABJRU5ErkJggg==", // 位图数据 Base64 字符串
  "iconColor": "#FF825EC2", // 通知栏中显示的图标颜色 - 不设置使用系统默认颜色 (不设置颜色可删除此项)
  "contributorName": "Mars" // 贡献者昵称
}

**Comment by moonbai** [comment]
![Screenshot_2022-04-07-11-17-42-579_com.fankes.notifyicondebugging.jpg](https://user-images.githubusercontent.com/34854875/162113337-212746c5-0b2b-4bf3-bf21-fbf9f2c2c30c.jpg)
手机端无法push，请大佬协助，感谢～

**Comment by fankes** [comment]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/37344460/162121944-7e2b8253-a96b-4617-962b-cad259683395.png">
