### ISSUE TITLE
图标适配-货拉拉

### ISSUE THREAD

**Issue by moonbai** [BetterAndroid/android-notification-icon-project#90]
{
  "appName": "货拉拉",
  "packageName": "com.lalamove.huolala.client",
  "isEnabled": true,
  "isEnabledAll": false,
  "iconBitmap": "iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAd0SURBVGiB7Zh/bFPXFcc/5z7HcWLaJF3CJshaQCAQ7SpBp2mr6NhKtQ1RqeqPaBCUKEvsNyhj2mDhj4kgVwWhiWkV66QK21RuUNgYG6BqbdVtoVHV0i3jl6p2mpQirYS0/CiwQH45tt/ZH37JnBA7CQ7rP/5KV3r3vfPOud97z73nnAsFFFBAAQUUUAAyHdmamhpfPsb8fr/GYrGhfHRkw5SIBAKBp4wxAWBOnvYc4CPgpXA4/FaeusZgUiK2bW8E9gJFM2FQVVVEBlX1+5FI5E8zoRMmIFJXV+cXER9AcXHxl4HXRGQOkFTVj0UkmYe9ImAeYFS1M5FIrJwpV/Nkdmzb3grsynhlAR5NY291dfW2UCikt2ts8+bN3qGhoeMi8rCILPD5fHcDM0LEZHZU9XGgOKN5XFfoBPaEQiEH0NttFy9eTKrq4Ihtx3GsmSAB41ZEVZ8HekVk5H1KRE4ODw+/GIvF/jNTRu8ExhCJRqPHQ6FQR0dHh6mqqlKAw4cPpz6foU0PE55awWDwMeARxrne6E8iV4aGhtpaW1uvTsdYTU2NVVZW9qYxZpWq9ovIbuBmNnlV7VHVd6LR6KXJdHvGvwgEAtUicgD4Ug4D6vP5qoFtU+RwC0TED+ycRCYFnG9qalq7f//+zlyyt8y4MeYm0K2qWU8nERkCzk1tyHnBAuZZlvVyfX393FyCE7pWQ0NDuWVZlapqAViWpQCpVEoAVHWgr6/vk+nun0zXAm44jvMD4NpEso7jiMfjaVbV77mvDohIIBwOJyaS9wA0NjbeZYypHPct5S4tI4tjzOgCesrKyu4NBAJjfojH45cPHDjQP0VeSWPMe+Fw+NNsArZtnxORvwKLgHWpVOo48MpEsqapqek+y7LeM8Z8mGf7oKSk5O2GhobyKRKZFOFw+LyqbgEGgSJjzJ5gMHj/hESMMfNEZDFQkmcrVdUHPB5PxUwRAYhEIq87jhNxA3MV8IJt26Xj5TxdXV3vLlq06FkR+WY+Bt005q3e3t7z+eiZAM7g4GCL3+9fDqwQkVWkT8vnSGcMwPTqkbwxbrNfAx7ItUcyEQgEHjLGtANlqtqvqo9Fo9G/jXwfH0ckFAplJefmWp8LotHoqWAw2AK84MagjcCtRAKBwEMi8nxPT09ZNmW2bZ8DtoTD4c/u5KCzIZFIRIqKirYB1cDCzG+jRIwxQWB1LkWq+g2gA3j5DoxzUsRisbht2yNxZEwwHyWiqm+KyGoga10uIj3JZPLdOzPM/DBKJBKJHK2rq/uz1+stziZcWlraHw6H4yN99xi8N5lMVliWdTWRSJzPp+Krra2t8Pv99zmO4xWRT3p7ez+davYwZrO7UXnSyGzbdpHjOOtUdSsw3+PxeIG41+s9Z9v27uvXrx+ZTvqycePGilQqtU1V14lIlWVZFnCzoqLi77Zt7wiHw6enRWQ81q9ff7ff7/+6qko8Hv+gtbW1h/SRHRKRZhHJvJAoBpYBr5SXly8EfkH61iQnbNsuSyaTvwdWiUjmiVkMrFHVrwYCgbXRaLQjl54J641RTcXF84FXgde8Xu93AILB4Bpgm0tiQFX/oKrNqvoq6fq7RERabNt+eDISJp287RKRR10Sl1T1RVVtAU6TnojZIrJvw4YNs3PpyrkijuM4gBERS0T8NTU1FvAj97+Eqm5oaWlpnzt37lPxeLytubm5PZFI/JJ0yrIVOEGOVVHVSlV9RkQMcNFxnO/u3bu3qLS0dGV3d/dPd+7c+WMReVpVFyWTyTVAjCxBPGdkr6+v/4LP5zsJzFPVK8CHIvI1oBT4x65du56orKx8A3gQSPX39/96y5YtTwLzVfWKiERUdfRwcAdcBywABlX1CFDrrsaOffv2vQ0cA8qAofb29pZDhw495wbAd0iv0g9Ju92xcDj85IjunCvS2tp6NRgM7hGRvW7C9q2M2fyssrJyCbDEnRCP3+9/1Ov19g8PD+PK/3ys249BiYisz9DXDTwDjGTPJYsXL14GDAB+YIXbUFU1xvwxU1nOPQIQiUReUtWngSPASdwaW0QePHv27DDQNzKWCxcupBKJxH1u3wGSEzVVTalqyn1WV98TAwMD7wMjNZBz6tSpL4rIPW4/5f5/Fdhx7dq132aOc9pJo23bv1LVnwAYY97YtGnT60uXLl3d3d3tiUajCy9fvrzAFd1H2k1ugeM4HhFRVbWMMbtF5H4gUVJS8pvt27dfLy8vX9nZ2SltbW1fSSaTVUDCcZyfOY7zL8uy/h2JRLrIyHxvi0hjY+Mcy7JOiMjIzMdV9aqIzOZ/rvrPvr6+FQcPHrw+mb5gMPg48Dt3HwDcIF1IVZG+WlUg2tXV9WxHR0fW69pp3/SdOXPm5rJly04YYx4B7gGKROQu0m7qAO8D62Ox2MdT0Xf69OmPli9fflFEVqiqz713nqWqiEhSRA45jrP16NGjOQP1bdcjtbW1FbNmzVoLfFtVq0TkkuM4fxkcHDzc1tZ2Y7r6bNteAqwFlpOuNruAYyJyPNuFw53ApIfGNPF/LfgKKKCAAgq4bfwXQ/IqVKCEV7QAAAAASUVORK5CYII=",
  "iconColor": "#FFFF6801",
  "contributorName": "Mars"
}

**Comment by moonbai** [comment]
![Screenshot_2022-04-20-20-35-06-084_com.fankes.notifyicondebugging.jpg](https://user-images.githubusercontent.com/34854875/164231481-8cd900d2-82cb-4df7-a468-0007d6c2060b.jpg)

手机端无法提交，请大佬协助push，感谢～

**Comment by fankes** [comment]
完了
