### ISSUE TITLE
图标适配

### ISSUE THREAD

**Issue by moonbai** [BetterAndroid/android-notification-icon-project#96]
{
  "appName": "微电子移动门户",
  "packageName": "com.goertek.mosmobile",
  "isEnabled": true,
  "isEnabledAll": false,
  "iconBitmap": "iVBORw0KGgoAAAANSUhEUgAAACgAAAAwCAYAAABjezibAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAASSSURBVFiF7ZnPbxRlGMc/zzszOzNtt2ttl1+KAaFLk6JoTLWxJW4iBD0A8YAYYtQD6Y3EAwnExuRNPHEi/gkeTQ/GkJAYL02aNJpAQhHqAQ+g+GMTFZYsdqGdeTzsstl2d9PS6RYO/R7fd97n+5lnnveded8R1kDW2gB4IY7jIYA4ji/dv3//1/Pnz88lje0kDXD69OnOVCp1UFU/N8a8JyJ5Y8xwKpW6MzQ0dHt6eno+SXw3KWAYhgOq+i6wX1U7q83bjDE3u7q6fgcuJYlvkgy21hoR2QsMA511XZ3Vtr3W2kQeiQaXSqXQGLML2Lm0T1V3Ai+WSqUwiYesZpC11gWeAXYDn6rq8abBRb6OouhLx3FuAHettQttBbTWmmKx6Gcyma3AEVU9DLwCPNtiyL/AFRG5sLCw8K3rugWgbK2NV+q54lk8NjbmhWGYC4LgJPAZcFREdlOpt1Y36ovIc6r6hjHmbRHJAn/lcrni5cuXVwS5ogyeOXMmE4bhQVX9WET2AX2q6rPyGo5F5AHwt6rOiMhXc3Nz3587d6643MBlM2it7XYc5zDwiYjsV9Us4PF45SHVMRkR2aqqfZ7nzeXz+VuTk5MPVg1orXXjOH7HGPMRMAp0PwZUK/nAJqBbRO5ms9kbs7Oz2uri5RbqHcaY48CbawQHgIikgRFVLe3Zs2cGuAk0hWyZwbGxMS+dTp8AjgLbWOWS1JpRAsB3HOefXC53pdWkaQporTXpdLoHGFfVASqPZa0lVGZ5dyqVunDgwIEHk5OTDVlsOgtLpVIYx/FrqtoPdLQB7pE6gJzv+6+2euM0BfQ8rwN4HegSkbV8tItUjd0FDFc9VwQovu9njDFviUioqm0DrMYOgLzv+xma1HkD4KlTp1JRFG0GXgZS7YKrU6rqtcla6y3tbFhment7fSCrqr3tfLx1Mqraq6rZcrnsAw8XdS69ulwuO3Ech+sEB9RqMTDGNCSsAVBEjDGmIdXroJSINPA0NPi+L3Ecr1v2aiDGOL7vN/g2fdUZY6Sds7dej3xaVVSiT/710AZgUm0AJtUGYFJtACZVM0CX9n5Ft1IHTd5siwCPHTvmAH3AwDpB1WsA6Ksy1LQIsL+/fxOQV9Wj60kGUPXMDw4Obq5vr9GOj49vd133A+CkiOxgDU5fH0ci0qGqO0QkHhkZ+W1qaupeDXB8fHy74zgnqpv0dm0zl5MjIhlV3WyMcUZHR29NTU3dc86ePdvjed6HIvI+sJfKJuZJyQV6RCTrOA7Dw8M/myAIdonIkacA7pECVR0EjgRBsMulcohTVNVfnjRZvVS1KCLdLvBDFEVfOI6TftJQS1QCrgnU1r+nThMTE1GifYe1toPKsVyr2i0D96y1/63WI9GPnDiODxljDgHPt7jkdhzH3wHfrNYj6Z+mLlXdR+WnTYNE5EdjzHQSg0RfM6p6FbgqIndEpHa2JyIqIndUdSaKopkkHokyWCgUZrds2XJRRHpU9SWqh02q+lBEflLVi4VCYTaJR+LNubXWnZ+f3+p53iCVo2KAP4Br169f/3NiYiJKEv9/i9NjfMwDHSsAAAAASUVORK5CYII=",
  "iconColor": "#FF407AB9",
  "contributorName": "Mars"
}

**Comment by moonbai** [comment]
请大佬协助push～

**Comment by fankes** [comment]
下次请自行提交PR，不再受理 issues
